### ISSUE TITLE
Intercept entries not sticking to the bottom if new ones are inserted before 

### ISSUE THREAD

**Issue by Sytten** [caido/caido#1]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

The intercept entries table doesn't stick correctly to the bottom of the page if some are added before.

### How to reproduce

1. Sort intercept entries by ID desc
2. Scroll to the bottom
3. Visit some website

### Environment & setup

OS: Mac OS
OS version: 10.14
Caido version: 0.7.2

**Comment by Corb3nik** [comment]
Fixed via caido/ui#239
