### ISSUE TITLE
Allow plugins to interact with the file api

### ISSUE THREAD

**Issue by Riddle1001** [caido/caido#1002]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description
Allow plugins to interact with the file api including:
creating, reading, updating, and deleting
### Use cases

Allow us to modify contents of a file without needing to reupload, create complex systems

**Comment by Sytten** [comment]
I need something more specific about the use cases. I feel this likely not an API we will want for the frontend since those files can be large (assuming we are talking about `hosted files`). We are planning for a backend plugin system soonish where that might be more appropriate.

**Comment by Riddle1001** [comment]
> I need something more specific about the use cases. I feel this likely not an API we will want for the frontend since those files can be large (assuming we are talking about `hosted files`). We are planning for a backend plugin system soonish where that might be more appropriate.

I am building a relatively complex shell plugin and it would nice to interact with Caido specific files, as well as create and modify them
![image](https://github.com/caido/caido/assets/75004732/080eb4f5-4a0d-4872-9b66-63dd356f9344)

**Comment by Sytten** [comment]
There is an api for the hosted files already, things like `uploadHostedFile` but I might not understand what you need

**Comment by Riddle1001** [comment]
> There is an api for the hosted files already, things like `uploadHostedFile` but I might not understand what you need

I think I could create a small file system from `uploadHostedFile` if `uploadHostedFile` has a content property but it looks like from the API it just takes name and path

**Comment by Sytten** [comment]
It is a bit complicated to use since it follows a weird graphql spec, maybe @Corb3nik can chime in for that.

**Comment by Corb3nik** [comment]
Main reason why we're reluctant to add a content property to the `HostedFile` is because we don't want to encourage plugin developers to have the bad habit of loading GBs of data in the UI.

Maybe we could expose a `content(start: Integer!, end: Integer!): Chunk!` property instead, and have users deal with chunks... I guess developers could still end up loading GBs of data...


@Sytten For this specific plugin, maybe the best would be to use a library like https://xtermjs.org/ that takes care of the UI, and have a backend plugin that feeds it data via websocket. https://xtermjs.org/docs/guides/flowcontrol/

**Comment by Riddle1001** [comment]
> Main reason why we're reluctant to add a content property to the `HostedFile` is because we don't want to encourage plugin developers to have the bad habit of loading GBs of data in the UI.
> 
> Maybe we could expose a `content(start: Integer!, end: Integer!): Chunk!` property instead, and have users deal with chunks... I guess developers could still end up loading GBs of data...
> 
> @Sytten For this specific plugin, maybe the best would be to use a library like https://xtermjs.org/ that takes care of the UI, and have a backend plugin that feeds it data via websocket. https://xtermjs.org/docs/guides/flowcontrol/

That would be great if you could add something like that, but I guess I could just wait until the backend API is done, assuming this will be something that is possible with the backend. If possible though, it'd be nice to have the ability to perform CRUD actions on the upload files, maybe not the create part if that is something you are really worried about, but being able to add or create a new wordlist automatically would be very nice.


Using xterm seems more ideal for mirroring a server's terminal, tried using it for my plugin, very odd to work with. the screenshot is stuff I showed all within the browser, parsing, interpreter, commands are all inside the browser

**Comment by Corb3nik** [comment]
@Riddle1001 Oh if creating / adding a new wordlist is enough for now, you can already do that.

This should do it:

```javascript
const blob = new Blob(["my-content"]) 
const file = new File([blob], "my-file.txt") 
Caido.graphql.uploadHostedFile({ input: {name: "myFile", file }}) 
```

Reading an existing wordlist isn't possible, but creating/deleting is

**Comment by Riddle1001** [comment]
> ```js
> const blob = new Blob(["my-content"]) 
> const file = new File([blob], "my-file.txt") 
> Caido.graphql.uploadHostedFile({ input: {name: "myFile", file }}) 
> ```

I see, I think I need to do almost everything, guess that is something that will be possible with the backend

**Comment by Sytten** [comment]
This is doable now in backend plugins

**Comment by Corb3nik** [comment]
This should be covered by the fs API in backend plugins + Files SDK frontend plugins.

Closing this via https://github.com/caido/proxy-frontend/pull/1685
