### ISSUE TITLE
Expose the HTTPQL builder function to javascript

### ISSUE THREAD

**Issue by Riddle1001** [caido/caido#1012]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description
Add something akin to `Caido.utils.HTTPQL(httpql: string): HTTPQLObject`
### Use cases
Allows plugins to use the function and apply it on intercept/logger requests

**Comment by Sytten** [comment]
The parser is already open source so you can include it in your plugin build. See https://github.com/caido/httpql
