### ISSUE TITLE
Active Match and Replace Rules Remain Active Despite Being Toggled Off in Default Collection

### ISSUE THREAD

**Issue by trev0ck** [caido/caido#1013]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

Active Match and Replace Rules are still part of the Active Rules set even after being toggled off.

### How to reproduce

1. Open the Caido application
2. Navigate to the Match & Replace panel.
3. In the 'Default Collection', toggle off any rule (e.g., 'Content-Length Replacement').
4. Navigate away from the settings and check the 'Active Rules' section.
5. Observe that the rules toggled off still appear in the 'Active Rules' contrary to the expected behaviour.

### Environment & setup

OS: Windows
Caido client: Caido for Windows

**Comment by Corb3nik** [comment]
@trev0ck Are you able to reproduce this reliably? 

I can't seem to get the same behavior on my end.

**Comment by Corb3nik** [comment]
Ok nevermind, I got it to work. Thanks 👍
