### ISSUE TITLE
Shortcuts set in desktop don't seem to be used when in browser

### ISSUE THREAD

**Issue by Sytten** [caido/caido#1015]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

User reported setting key bindings in the app, but then had to re-set them in the browser. They should carry over.

**Comment by Corb3nik** [comment]
Closing this, can't reproduce this issue.
