### ISSUE TITLE
Cannot Add Header Using Match&Replace

### ISSUE THREAD

**Issue by Rhynorater** [caido/caido#1021]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

We should be able to add a header by leaving the `Search Term` field empty and adding a header to the `Replace term` and setting the strategy to `Request Header` in Match&Replace.  This works in the `Before` and `After` test section below, but it does not actually add the header to the requests. 

This is a very important behavior because hackers are often required to do this when testing.

### How to reproduce

* add a new M&R rule
* Set Strategry to Request Header
* Search term -> nothing
* Replace term "test: test"
* Click the test button and note that the header has been added in the example request
* Send a request through HTTP Proxy and note that there is no modification occuring.

### Environment & setup

OS: 
OS version: 
Caido client: 
Caido version:

**Comment by Rhynorater** [comment]
JK, it was some sort of temporal bug that I cannot reproduce. This works as intended.

**Comment by Sytten** [comment]
Are you sure you dont have a condition set? And the rule is enabled?
