### ISSUE TITLE
Drop webview in desktop application

### ISSUE THREAD

**Issue by Sytten** [caido/caido#1024]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Due to the many problems with native webviews we are rewritting our desktop application from Tauri to electron. This will mean better performances for Linux and less bugs overall.

**Comment by Corb3nik** [comment]
Closed via https://github.com/caido/proxy-desktop/pull/185
