### ISSUE TITLE
add httpql  in intercept page

### ISSUE THREAD

**Issue by abdulsec** [caido/caido#1029]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

I would be great to  add httql filter in    intercep page to show only the request  or path that interest you

### Use cases

showing only the request that interest you with httpql  query without relying only in scope

**Comment by Sytten** [comment]
Dupe of https://github.com/caido/caido/issues/580

**Comment by Corb3nik** [comment]
Duplicate of #580
