### ISSUE TITLE
Commands menu won't close

### ISSUE THREAD

**Issue by f8thl3ss** [caido/caido#1034]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description
In certain situation, the Command Palette won't close after pressing `esc`.

### How to reproduce
Open the Command Palette, click outside the input area, notice that the menu won't close.

### Environment & setup

OS: Linux (Gnome)
OS version: Linux nixos 6.9.0 #1-NixOS
Caido client: Chrome
Caido version: 0.36.1

**Comment by Corb3nik** [comment]
Duplicate of https://github.com/caido/caido/issues/992
