### ISSUE TITLE
Caido Appimage will not open on Kali Linux running in WSL2

### ISSUE THREAD

**Issue by ponlayookm** [caido/caido#1038]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

When opening the Appimage via command line, Caido's blank Windows show up.
The terminal displayed these errors:
$ /opt/caido-desktop-v0.36.1-linux-x86_64.AppImage
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
Could not determine the accessibility bus address
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen

### How to reproduce

$ chmod 755 /opt/caido-desktop-v0.36.1-linux-x86_64.AppImage
$ /opt/caido-desktop-v0.36.1-linux-x86_64.AppImage
### Environment & setup

OS: 
Kali-Linux on Windows WSL2
OS version: 
Kali 2024.2
Linux DESKTOP-LEPB3RE 5.15.146.1-microsoft-standard-WSL2

Caido client: 
Caido Desktop
Caido version: 
caido-desktop-v0.36.1-linux-x86_64
![Annotation 2024-05-21 024856](https://github.com/caido/caido/assets/139254728/eacd71ae-4ef6-4699-9e87-f2db749569af)

**Comment by Sytten** [comment]
This is probably a problem with Tauri, but since we are moving to electron it likely wont be fixed before that. We suggest using the CLI instead.

**Comment by Corb3nik** [comment]
Closed via https://github.com/caido/proxy-desktop/pull/185
