### ISSUE TITLE
Add HTTPQL for more columns

### ISSUE THREAD

**Issue by shriyanss** [caido/caido#1056]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description
There are some columns, for which HTTPQL isn't available, e.g. when I wanted to set the traffic source to "replay" in the logging tab, there weren't any filters for it.

### Use cases
This can be used to filter more effectively

**Comment by shriyanss** [comment]
Another idea I've got now:-

**Comment by Sytten** [comment]
Agreed we will have to improve that, you can for now go in `Advanced` (next to the search bar) to select the source. We need to rework the backend section of that filtering so it will be included when we do that rework.
