### ISSUE TITLE
Unintended text selection on replay tab data

### ISSUE THREAD

**Issue by SanderShark** [caido/caido#1066]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

When moving a replay session from one collection to another, sometimes there is arbitrary text selected in the request box. Its extremely inconsistent and likely something very few people are experiencing due to platform and use case.

As @Sytten suggested this is mostly for UI redesign/replacement tracking purposes. 

### How to reproduce
Video:
https://github.com/caido/caido/assets/134541524/6603acd5-01aa-4528-9f31-6a1530302051

1. Open ~20 replay sessions with enough data to fill the entire length of the page, its possible line breaks are a factor as well so make sure there are some. 
2. Move sessions to the second collection one by one until you find one selecting text in the replay session displayed to the right.

### Environment & setup

OS: EndevourOS (Arch Linux) x86_64
OS version: 6.9.2-arch1-1
Caido client: Caido Desktop
Caido version: 0.37.0

**Comment by Corb3nik** [comment]
@SanderShark Are you still able to reproduce this on the latest version v0.40.0?

**Comment by SanderShark** [comment]
Just checked it out, and no, can't reproduce anymore. The whole thing is way smoother now as well. Major upgrade!
