### ISSUE TITLE
Online Marketplace for Plugin/Workflow Management

### ISSUE THREAD

**Issue by hahwul** [caido/caido#1072]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Currently, Caido provides installation and management of plugins and workflows through a file. I would like to propose the addition of an online marketplace for managing plugins and workflows (similar to Burp's BApp store and ZAP's marketplace).

> I searched GitHub for related discussions but couldn't find any, so I'm opening this issue. If there is a related issue, please feel free to close this one! Sometimes, I work on writing plugins and workflows for testing. However, since [EvenBetter](https://github.com/bebiksior/EvenBetterExtensions) already provides similar functionality through its marketplace, I'm considering whether I should develop my plugin to be dependent on EvenBetter for better usability. If it's officially supported, I probably won't need to rely on EvenBetter.

### Use cases

Check available plugins and workflows, and easily install/uninstall/update them with a click.

**Comment by Sytten** [comment]
Agreed on that, our plan is to start with a simple GitHub repo for the moment and have a full on marketplace later (probably in 2025).
