### ISSUE TITLE
Unable to enter long scope domain

### ISSUE THREAD

**Issue by Sytten** [caido/caido#1074]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

User reported not being able to enter a long domain like ` *.mindbodyspiritcoaching.online `

**Comment by Corb3nik** [comment]
Closing this for now, everything looks fine on my end.

![Image](https://github.com/caido/caido/assets/6225588/946cb3f6-83e6-41a7-8987-5f920e732a42)



![Image](https://github.com/caido/caido/assets/6225588/52d53ba8-5eb5-4cf3-be16-d26cfb0de122)
