### ISSUE TITLE
SDK Console debug() not working

### ISSUE THREAD

**Issue by offftherecord** [caido/caido#1086]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

The SDK function sdk.console.debug() does not log.

### How to reproduce

1. Using an active workflow and a javascript node, try to log a message with sdk.console.debug("test message");
2. Review the backend logs for your OS. 

### Environment & setup

OS: MacOS
OS version: Sonoma 14.5
Caido client: Desktop
Caido version: 0.37

**Comment by Sytten** [comment]
You need to enable debug logs with --debug in the CLI or the debug setting in the desktop app.

**Comment by offftherecord** [comment]
Ah okay, thank you!
