### ISSUE TITLE
HTTPQL input box is not scrollable

### ISSUE THREAD

**Issue by rew1nter** [caido/caido#1090]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description
![image](https://github.com/caido/caido/assets/64508791/0cfcb898-8b10-4638-9efd-3e4fb6b7d863)

### How to reproduce
Write a large query and shrink the Caido window size 

### Environment & setup

Caido client: Chromium
Caido version: Caido 0.37.0

**Comment by Sytten** [comment]
I think those are mostly fixed in 0.38.0 @Corb3nik

**Comment by Corb3nik** [comment]
Yep, this should be fixed in v0.38.0. @rew1nter let me know if you think otherwise and we'll re-open it :)
