### ISSUE TITLE
Caido hangs when `Other` status code is unchecked

### ISSUE THREAD

**Issue by rew1nter** [caido/caido#1103]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description
![image](https://github.com/caido/caido/assets/64508791/581375d8-eb1f-4a9d-ae65-f25dbab5d9d4)

### How to reproduce
Just replicate the screenshot

### Environment & setup

OS: Arch
Caido client: Chromium
Caido version: Caido 0.38.0

**Comment by Sytten** [comment]
It might be related to https://github.com/caido/caido/issues/1092
