### ISSUE TITLE
Conditional Intercept

### ISSUE THREAD

**Issue by Rhynorater** [caido/caido#1106]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

I think it would be awesome to have a conditional intercept. Essentially, you'd just keep the HTTPQL bar at the top of the intercept tab, and allow the user to define an HTTPQL query which would be the only thing intercepted. Otherwise, it would just flow through.

### Use cases

For when you're trying to catch one request in a flow of requests.

**Comment by Sytten** [comment]
Closing in favour of https://github.com/caido/caido/issues/580
