### ISSUE TITLE
Delayed response on the replay tab is blank

### ISSUE THREAD

**Issue by 0xatul** [caido/caido#111]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description
Replay doesnt seem to wait for the response long enough, which is quite annoying if you happen to have the ability to attach a debugger to the application you are testing and arent able to get back responses for any requests which triggers the breakpoint set.

### How to reproduce
1. Put a breakpoint somewhere in the application
2.  send a request to the application which triggers the breakpoint, and resume the application 

Here's a clip demonstrating it:
The first request triggers the breakpoint, and there were no breakpoints when sending the second request
![caido_repro gif](https://user-images.githubusercontent.com/52250292/148657833-f7937537-f24f-4a28-9e32-b53d89e45806.gif)

### Environment & setup

OS: Windows 10
OS version: 21H1 BUILD 19043.1415
Caido version: 0,7.17

**Comment by Corb3nik** [comment]
Closed via caido/engine#316
