### ISSUE TITLE
Caido.storage.onChange Isn't Functioning

### ISSUE THREAD

**Issue by Rhynorater** [caido/caido#1115]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

It appears that `Caido.storage.onChange` isn't being called when the storage is updated.

https://www.loom.com/share/bd0b0918cffb403c93d681c7f359346d

Password: https://discord.com/channels/843915806748180492/1093642937411322007/1258618754036928643

### How to reproduce

I added Ian to the Expaido repo - if y'all need to reproduce tomorrow, try this:
1. Clone repo
2. Run `pnpm install && pnpm build`
3. Install zip file
4. Go to HTTP history and select some text
5. Control-K "Add Expaido Entry" -> add some text
6. Go to the Expaido page and note that the table did not refresh.

### Environment & setup

OS: Windows
OS version: 11
Caido client: Dekstop
Caido version: 0.38

**Comment by Corb3nik** [comment]
Fixed via https://github.com/caido/proxy-frontend/commit/870f8d77f0913a0e1af8687147796b1393c6fef9#diff-e91bf516693e458e718761945dc0bf1cd250b1cf28c5abbc68357d18e8614190R12-R14
