### ISSUE TITLE
Forwarded response doesn't contain edited content

### ISSUE THREAD

**Issue by Corb3nik** [caido/caido#1133]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### How to reproduce

Intercepted responses aren't forwarded with new manually edited content

### Environment & setup

OS: 
OS version: 
Caido client: 
Caido version:

**Comment by xaferima** [comment]
me too

**Comment by Sytten** [comment]
@xaferima We fixed it, it will in the next release or the nightly build if you are paid user

**Comment by xaferima** [comment]
> the nightly build if yo

Thanks for ur answer... I am a pro user, how do I get the  nightly build?

**Comment by Corb3nik** [comment]
@xaferima If you join our Discord, we can give you the role to access the nightly build channel :)
