### ISSUE TITLE
atob and btoa in JavaScript Node

### ISSUE THREAD

**Issue by Rhynorater** [caido/caido#1135]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

The JS engine being used for the JS SDK is missing `atob` and `btoa`.

**Comment by Sytten** [comment]
Those are legacy APIs, we will implement them but the current way of doing things is with a buffer `Buffer.from(b64string, 'base64')`
