### ISSUE TITLE
Undo (Control-Z) no longer works after you switch Replay tabs.

### ISSUE THREAD

**Issue by Cache-Money** [caido/caido#1145]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

Undo (Control-Z) no longer works after you switch Replay tabs. This impedes workflow because you cannot quickly test a different payload (Say testing another ID for an IDOR) and undo it afterwards to the original value if you happen to switch tabs before undoing it.

### How to reproduce

1. Put two tabs in Replay.
2. Make a change in one.
3. Click to the other tab.
4. Click back to the original tab.
5. Press Control-Z and notice you cannot undo the text.

### Environment & setup

OS: Windows
OS version: 10
Caido client: Windows desktop
Caido version: 0.39

**Comment by Sytten** [comment]
We added back the saving of the current changes of the editor when switching tabs, but the history must be discarded.
