### ISSUE TITLE
HTTPQL  filtering based on length (e.g., resp.len or req.len)

### ISSUE THREAD

**Issue by deathflash1411** [caido/caido#1150]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

HTTPQL  filtering based on length (e.g., resp.len or req.len)

**Comment by Sytten** [comment]
Length of the body or full length?

**Comment by Sytten** [comment]
Added full length for now, we can add body length later
