### ISSUE TITLE
Listing port reset to 8080 after upgrade to Desktop version 0.40.0 (0.40.0)

### ISSUE THREAD

**Issue by sasinomasec** [caido/caido#1162]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

I upgrade to version 0.40.0 (0.40.0) and after started Caido I notice that the Listing Port has been rest from my original port to 8080

### How to reproduce

1. Use Caido version<0.40.0 and set your listing port to 9999.
2. Upgrade to 0.40.0.
3. Start Caido and check your listing port. 
The port will be reset to 8080

### Environment & setup

OS: Mac OS
OS version: Sonoma 14.5 (23F79)
Caido client: Desktop
Caido version: 0.40.0

**Comment by Corb3nik** [comment]
Hi @sasinomasec

Thanks for the issue! This is expected behaviour because we completely switched to a new system, which removed your existing instance list.

Future upgrades should not reset though, if it does, let me know and I'll open this issue back up :)

**Comment by sasinomasec** [comment]
Thanks @Corb3nik ,

What is the meaning of "which removed your existing instance list." I still saw my instance list, only the port has changed.

**Comment by Corb3nik** [comment]
@sasinomasec 

If you had multiple instances in v0.39.0, upgrading to v0.40.0 resets the list to a single instance with default port of 8080.

In your case, you only had 1 instance with a custom port, and upgrading reset the instance back to 8080.

**Comment by sasinomasec** [comment]
thanks for your clarification
