### ISSUE TITLE
Add a way to show node ID in the workflow UI

### ISSUE THREAD

**Issue by Sytten** [caido/caido#1168]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Add a way to show the node ID in the workflow UI so you can more easily map errors to their origin.

### Use cases

Debug node better

**Comment by Corb3nik** [comment]
Closing this, as we show the node alias in error messages now. Node aliases' are easier to work with than Node IDs for a user, so this use case should be covered already.
