### ISSUE TITLE
Header value moves to next line before filling the current one

### ISSUE THREAD

**Issue by rew1nter** [caido/caido#1171]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description
![image](https://github.com/user-attachments/assets/d39d00de-549d-4989-8ca4-6ffe58a8425e)

### Environment & setup

Caido client: chromium
Caido version:  0.40.0

**Comment by Corb3nik** [comment]
Hey @rew1nter, what would be the expected behaviour here? The only options I have are what https://developer.mozilla.org/en-US/docs/Web/CSS/white-space offers.

**Comment by rew1nter** [comment]
Fortunately, I cannot read a single line of CSS. 

All I can tell you is, the cookie should fill the first line before moving to the next
