### ISSUE TITLE
Request made by replay and automate don't trigger passive workflows

### ISSUE THREAD

**Issue by vinirossa** [caido/caido#1176]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

I think this would be a feature, but I'd like to know why when you send requests through the "Replay" and "Automate" interfaces, the passive workflows that use the "On Intercept Request" and "On Intercept Response" doesn't get triggered. I'm new to this software and I built a workflow to analyze the request response to look for XSS vulnerabilities using the JavaScript node. So it's really important that it gets triggered by the "Automate" page where I do the massive testing but it seam that passive workflows are only activated by external requests like my browser. Is there an alternative to this? Am I doing something wrong?

Ps.: I tried using the active workflow, but I need to manually run it for each one of the requests that are listed within my "Automate" session, making it not practical at all.

### Use cases

- Make requests made by "Replay" and "Automate" pages triggers the passive workflows as they are triggered by external requests that passes through the proxy.

**Comment by Sytten** [comment]
They are not meant to trigger the passive workflow at the moment. Only stuff going through the proxy does. It would be a feature request.

**Comment by vinirossa** [comment]
> They are not meant to trigger the passive workflow at the moment. Only stuff going through the proxy does. It would be a feature request.

Hm, I see. That would be really nice and help a lot to test for XSS and SQLi. Somehow when a I changed the intercept mode to "Queueing" my automate and replay requests started to trigger the passive workflows. I don't know if this is supposed to happen but for now is going to help me a lot. 

Thank you for replying me. I really appreciate it and love this software.
