### ISSUE TITLE
Replay Jumps When Adding New JSON Entity and Request is Too Long

### ISSUE THREAD

**Issue by Rhynorater** [caido/caido#1189]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

When the HTTP request is too long, the JSON editor will jump around.

### How to reproduce
1. Create a long request such that you have to scroll and can no longer see `GET /...` or whatever
2. Put content-type application/json
3. Change the json structure

loom: https://www.loom.com/share/2fcd9ac33aac428b807e903565b49b45

### Environment & setup

OS: 
OS version: 
Caido client: 
Caido version:

**Comment by Corb3nik** [comment]
@Rhynorater Any chance you can reproduce this on the latest nightly build?
