### ISSUE TITLE
Invalid Selection in Response Dropdown Bricks Workflow

### ISSUE THREAD

**Issue by Rhynorater** [caido/caido#1191]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

You can select an invalid option on the `Response` dropdown in a node which will trigger an error and brick the workflow. This should not be possible.

![Image](https://github.com/user-attachments/assets/d777f27c-58a3-4836-b08b-3be6230ff5f6)

**Comment by Corb3nik** [comment]
Closed via https://github.com/caido/proxy-frontend/pull/1649
