### ISSUE TITLE
Frontend SDK: registerItem with SettingsMenuItem overrides entire page including navigation bar

### ISSUE THREAD

**Issue by bebiksior** [caido/caido#1212]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description
It would be awesome to have `keepNavigationBar` property in `SettingsMenuItem`. Currently, afer navigating to the Example settings tab in this example, it will remove everything including settings navigation bar.
```js
  sdk.menu.registerItem({
    type: "Settings",
    label: "Example",
    path: "/example",
  });
 ```

https://github.com/user-attachments/assets/55b2103f-fbbb-4698-821e-7a00f461b8b3

### Use cases
Plugins could use settings page tabs to add plugin-related settings there. Disappearing settings navigation bar is super annoying.

**Comment by Corb3nik** [comment]
@bebiksior This happens because the path doesn't start with `/settings/`. If it starts with `/settings/` it'll load the navbar.

I'll make sure `sdk.menu.registerItem() throws if your path doesn't include `/settings/`
