### ISSUE TITLE
Selected Scope is Not Included in `Caido.scopes.getScopes()`

### ISSUE THREAD

**Issue by Rhynorater** [caido/caido#1242]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Include an `isSelected` attribute in `Caido.scopes.getScopes()` response for each scope.

**Comment by Sytten** [comment]
This depends on the currently selected tool @Rhynorater since we don't have a global scope at the moment.

**Comment by Corb3nik** [comment]
Work on this is already started FYI: https://github.com/caido/proxy-frontend/pull/1694/files

**Comment by Corb3nik** [comment]
@Sytten Work on this is already started FYI https://github.com/caido/proxy-frontend/pull/1694/files
