### ISSUE TITLE
Plugin Re-install Resets Caido Storage

### ISSUE THREAD

**Issue by Rhynorater** [caido/caido#1249]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

When you re-install a plugin (ie, for doing an update) the plugin storage `Caido.storage.get` is reset and the user loses their configuration.

### How to reproduce

1. Set some storage in a plugin
2. Uninstall the plugin
3. Reinstall the plugin
4. Note that the storage is gone

### Environment & setup

OS: 
OS version: 
Caido client: 
Caido version:

**Comment by Sytten** [comment]
I will classify that as expected behaviour
