### ISSUE TITLE
Request Placeholders don't update Content-Length

### ISSUE THREAD

**Issue by bebiksior** [caido/caido#1251]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description
Content-Length is not being updated if we have a placeholder that changes the length of the request

### How to reproduce
1. Create a request with placeholder that changes the length of request (adds new characters etc) 
2. Send it to your server and notice wrong Content-Length header

### Environment & setup

OS: 
OS version: 
Caido client: 
Caido version:

**Comment by Sytten** [comment]
Thats in replay correct?

**Comment by bebiksior** [comment]
@Sytten Yeah, it's on the replay page

**Comment by Sytten** [comment]
It works here, is it possible that you removed the `\r\n\r\n` or disabled the update of CL option? @bebiksior 
<img width="231" alt="Screenshot 2024-11-01 at 4 54 57 PM" src="https://github.com/user-attachments/assets/0aadf1da-1048-4052-88a8-11b0b6104750">
<img width="172" alt="Screenshot 2024-11-01 at 4 55 05 PM" src="https://github.com/user-attachments/assets/872e41c5-1b62-459b-bd20-f320d8f710ef">

**Comment by bebiksior** [comment]
I couldn't reproduce it again, I guess I did something wrong. Will reopen if it happens again :D
