### ISSUE TITLE
Allow numbers in ID of workflow plugin

### ISSUE THREAD

**Issue by Corb3nik** [caido/caido#1256]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

Given the following plugin manifest file

```
{
  "id": "pwnfox",
  "name": "PwnFox",
  "version": "0.0.1",
  "description": "Integration with the PwnFox browser extension",
  "author": {
    "name": "SyzikSecu"
  },
  "plugins": [
    {
      "kind": "workflow",
      "id": "base64-decode",
      "name": "Passive Workflow",
      "definition": "base64-decode/definition.json"
    }
  ]
}
```

The ID `base64-decode` in the `plugins` field is invalid. THis is due to the digits

The docs suggest that this should be possible for frontend/backend plugins. We should make it consistent with workflow plugins too. https://developer.caido.io/reference/manifest.html#plugins-fields

**Comment by Sytten** [comment]
Current regex: `^[a-z]+(?:[_-][a-z0-9]+)*$`
New regex: `^[a-z][a-z0-9]+(?:[_-][a-z0-9]+)*$`
