### ISSUE TITLE
Casing inconsistency on isTLS and isTls

### ISSUE THREAD

**Issue by Rhynorater** [caido/caido#1262]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

![Image](https://github.com/user-attachments/assets/552a9b9b-68a1-4677-9013-f458dd467101)

### Environment & setup

OS: 
OS version: 
Caido client: 
Caido version:

**Comment by Sytten** [comment]
we settled on `isTLS`
