### ISSUE TITLE
shortcuts for the convert workflows.

### ISSUE THREAD

**Issue by saymenn** [caido/caido#1272]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

- So what I have in mind is either making some builtin shortcuts for url decoding/encoding or you can provide some sort of a dashboard for users to setup their own shortcuts for caido in general.

### Use cases

- It would be nice to just ctrl+U a highlighted string to url encode it! :D

**Comment by Corb3nik** [comment]
Duplicate of https://github.com/caido/caido/issues/606
