### ISSUE TITLE
WSL Should Be A Shell for Caido Shell Nodes

### ISSUE THREAD

**Issue by Rhynorater** [caido/caido#1302]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

I would be great to have WSL as a value in this dropdown:
![Image](https://github.com/user-attachments/assets/c196165d-cda2-4f92-95ee-f9881e287bcf)

There is some information on how to use WSL In a Shell Node here:
https://docs.caido.io/reference/workflows/convert/coding_nodes.html#shell-node

But it is not great, and it is only categorized under `Convert` not under `Active` workflows.

### Use cases

When hackers want to use active workflows to trigger some calls to WSL in Windows.

**Comment by Sytten** [comment]
Now part of our open source https://github.com/caido/shell_exec
