### ISSUE TITLE
Deleting a project doesn't make it disappear from UI 

### ISSUE THREAD

**Issue by Sytten** [caido/caido#132]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

Deleting a project (confirmed on Windows for now) doesn't make it disappear in the list without a page refresh. 

### Environment & setup

OS: Windows
Caido version: 0.9.0

**Comment by Corb3nik** [comment]
Definitely something weird going on that only affects Windows.

**Comment by Corb3nik** [comment]
Seems to be fixed via https://github.com/caido/proxy-backend/pull/367
