### ISSUE TITLE
RequestSpecRaw doesn't parse characters like \x85 correctly  

### ISSUE THREAD

**Issue by bebiksior** [caido/caido#1331]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description
Looks like `RequestSpecRaw` doesn't parse characters like `\x85` correctly.

Request sent with:
```js
  const req = new RequestSpecRaw("http://127.0.0.1");
  req.setRaw("GET /admin\x85 HTTP/1.1\r\nHost: 127.0.0.1\r\n\r\n");
```

is different than request sent with:
![Screenshot 2024-11-25 at 20 25 49](https://github.com/user-attachments/assets/eeb023ff-5a95-4007-a723-65b48c4b5039)

(placeholder has URL decode)

### How to reproduce
1. Obtain Interactsh subdomain at https://app.interactsh.com/#/ 
2. Send request via backend plugin with this code
```js

async function testSendRequest(sdk: SDK) {
  console.log("Testing send request");
  const req = new RequestSpecRaw("URL");
  req.setRaw("GET /admin\x85 HTTP/1.1\r\nHost: HOST\r\n\r\n");

  const res = await sdk.requests.send(req);
  console.log(res?.response.getRaw().toText());
}
```
3. Send request via replay:
```http
GET /admin%85 HTTP/1.1
Host: fhtgwsvzxjlavunwpuyrbl66w2jw2m6yv.oast.fun

```
- make sure to add a placeholder on %85 with URL decode
4. Go to your Interactsh instance and notice that these two requests are different. 

### Environment & setup

OS: 
OS version: 
Caido client: 
Caido version:

**Comment by Sytten** [comment]
This is expected if you use a string. @Rhynorater also had a similar issue when trying to do a `setPath` with invalid unicode.
You need to pass it a `Uint8Array` or something like it that is binary based, otherwise the conversion of strings from JS to Rust will mess up your thing.

**Comment by bebiksior** [comment]
Thanks! Got it working :D
