### ISSUE TITLE
Boolean check on dedupe key in finding, before attempting to create finding

### ISSUE THREAD

**Issue by VasilyKaiser** [caido/caido#1357]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

It would be nice to have a way to check if particular `dedupeKey` is present in findings, before attempting to create a finding.
Maybe something like a switch inside findings node to make it only do boolean check on `dedupeKey`.
So the flow could be: Start -> If/Else -> Finding (with switch for `dedupeKey` ON) -> in case it's false proceed to do something with request/response and record it in findings.

### Use cases

I could do something like this and avoid wasting up to 10 sec of my workflow process power per request.
![image](https://github.com/user-attachments/assets/5a17be60-ca98-491c-9234-8cf3c949c830)

**Comment by Sytten** [comment]
Alright for the next release we are adding a few ways to do this:

**Method 1**
Create Finding 1 swapped for a `Javascript` node with the code:
```js
export async function run({ request, response }, sdk) {
    if (await sdk.findings.exists("mydedupekey")) {
      return "true";
    } else {
      return "false";
    }
}
```
Then you put the output of the `Javascript Node` into the `If/Else` and it will correctly go in the right branch.

**Method 2**
Create Finding 1 + If/Else swapped for a `Check Finding` node.
This new node will take as input the `dedupeKey`, but currently we don't have a syntax to infer the string so your options are limited.
This new node has a True/False output similar to Http Matches.

**Method 3**
Create Finding 1 + If/Else swapped for a `If/Else Javascript` node.
This new node will take as input the Request/Response similar to a `Javascript` node but expect a boolean as output.
So the script will look like:
```js
export async function run({ request, response }, sdk) {
    return await sdk.findings.exists("mydedupekey");
}
```
