### ISSUE TITLE
Sending requests from replay tab are to slow. About 1s delay

### ISSUE THREAD

**Issue by ElizarBatin** [caido/caido#1367]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

Sending requests from replay tab are to slow. About 1s delay

Comparison between caido and curl
![1733379774](https://github.com/user-attachments/assets/da627a2a-54a8-4f39-b532-d5fdca54230f)
![1733379674](https://github.com/user-attachments/assets/d2f99a03-3408-4443-b210-753a60a154ca)

### Environment & setup

OS: Arch linux
OS version: Linux archlinux 6.11.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 22 Oct 2024 18:31:38 +0000 x86_64 GNU/Linux
Caido client: Caido Desktop
Caido version: 0.8.0

**Comment by Sytten** [comment]
That is on purpose to see if more data is coming from the connection, curl would miss data exceeding the content-length. Add a Connection: close header to prevent that behaviour.
