### ISSUE TITLE
Add grace period for right click menu

### ISSUE THREAD

**Issue by Sytten** [caido/caido#139]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Add "grace period" on the right click menu so that if you accidentally move your mouse cursor outside of the box, everything doesn't instantly disappear

**Comment by Corb3nik** [comment]
This is fixed with new context menu implementation
