### ISSUE TITLE
Add match&replace feature

### ISSUE THREAD

**Issue by sw33tLie** [caido/caido#150]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

It would be very useful to have a match&replace feature for proxied HTTP requests.

### Use cases

Editing incoming requests for various tests.

**Comment by Corb3nik** [comment]
Closed via caido/proxy-frontend#601

**Comment by Corb3nik** [comment]
https://user-images.githubusercontent.com/6225588/188485033-a0a6f501-f794-49b4-a897-388eb54e8123.mov
