### ISSUE TITLE
Projects on windows are not deleted properly

### ISSUE THREAD

**Issue by Sytten** [caido/caido#153]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

It looks like projects on windows are not properly deleted from the filesystem

### Environment & setup

OS: Windows
Caido version: 0.10.X

**Comment by Corb3nik** [comment]
Seems to be fixed via caido/proxy-backend#367
