### ISSUE TITLE
Images should be of the same size in the certificate installation steps

### ISSUE THREAD

**Issue by Sytten** [caido/caido#155]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

Images are not all the same size in the certificate installation steps, we can do better :)
We should also take the opportunity to compress them.

**Comment by Corb3nik** [comment]
Images seem to be the same size on my end
<img width="911" alt="Screen Shot 2022-09-28 at 9 18 44 AM" src="https://user-images.githubusercontent.com/6225588/192788862-8c9dd5d1-cd8d-4be5-ae15-a596cb7cb628.png">
