### ISSUE TITLE
Improve installation process

### ISSUE THREAD

**Issue by Corb3nik** [caido/caido#157]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

As we support more and more users, asking people to have prior knowledge of the command line in order to run Caido becomes less realistic.

Let's make Caido easier to install. Some ideas:
- macOS: Installer / Packaging into an .app
- Linux: Install scripts? Integration with package mangers?
- Windows: Installer

**Comment by Sytten** [comment]
This is not relevant anymore
