### ISSUE TITLE
Shortcut to cycle through replay session entries

### ISSUE THREAD

**Issue by Corb3nik** [caido/caido#161]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Add a shortcut to cycle through replay session entries (go to previous / go to next).

Shortcut ideas: Cmd+Shift+LeftArrow / Cmd+Shift+RightArrow

**Comment by Sytten** [comment]
Use suggested `CTRL+z` and `CTRL+SHIFT+z` on [Discord](https://discord.com/channels/843915806748180492/902965396397752370/1131354390431809668)

**Comment by Corb3nik** [comment]
Duplicate of #1020
