### ISSUE TITLE
Shortcut for "Go to replay"

### ISSUE THREAD

**Issue by Corb3nik** [caido/caido#166]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Doing the action of sending to replay is often followed up by a navigating to the replay page.

Might be a good idea to create a shortcut for both actions combined.

Shortcut ideas:
 - Ctrl + Shift + R

**Comment by wbowling** [comment]
Could this be the default behaviour since I think it's probably the flow that you want the majority of the time? Could add a shortcut `Ctrl + Shift + R` that does not go to the replay if both flows are required

**Comment by Corb3nik** [comment]
Yeah, that's a good idea 👍
