### ISSUE TITLE
Shortcut tab not responsive to browser windows size/resolution

### ISSUE THREAD

**Issue by theJuan1112** [caido/caido#168]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

Shortcuts Tab is not responsive  i.e. it does not resize the content depending on the browsers size/resolution

### How to reproduce

Resize browser windows while on shortcuts tab

### Environment & setup

OS: Windows
OS version: 10
Caido version: 0.11
![caido notok](https://user-images.githubusercontent.com/57808488/157300471-2eca2acc-e500-4a96-863d-410a5ff6774f.png)
![caido ok](https://user-images.githubusercontent.com/57808488/157300474-03a60ab6-a01f-4176-aa8f-108bc82a9c39.png)

**Comment by theJuan1112** [comment]
Actually, I am seeing the same issue with all the settings tabs. i.e License,CA,etc..

**Comment by Corb3nik** [comment]
Nice find, I'll get that fixed for next release 👍
