### ISSUE TITLE
Add a feature to save  current encoding chains as preset

### ISSUE THREAD

**Issue by Neolex-Security** [caido/caido#171]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

It would be nice to be able to save some preset inside the convert tab to save some chains of encodings instead of having to recreate it every time manually 

### Use cases

There could be a save preset button that save the current chain and save it and add it inside the left tab

**Comment by Corb3nik** [comment]
Closed via https://github.com/caido/proxy-frontend/pull/934
