### ISSUE TITLE
Panel resize persistence

### ISSUE THREAD

**Issue by Corb3nik** [caido/caido#172]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Currently, panel resizing is saved in the browser's localstorage. Emptying your browser storage will reset users' panel customization.

Ideally, we should save those in the global config file instead.

- [x] caido/proxy-backend#381

**Comment by Rhynorater** [comment]
If possible, I would like to be able to resize the different panels without having to hit the `Edit Layout` button. I often resize my panel based off of the response body size, so it would be ideal to be able to do this in one click-and-drag.

**Comment by Corb3nik** [comment]
Tracking the resize request in https://github.com/caido/caido/issues/375
