### ISSUE TITLE
Switching between pages is slow

### ISSUE THREAD

**Issue by Corb3nik** [caido/caido#185]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

Switching between pages is slow sometimes

**Comment by Corb3nik** [comment]
The slowness is caused by the editor initialization. More specifically, the loop used to deactivate all monaco shortcuts.


<img width="1440" alt="Screen Shot 2022-03-29 at 1 58 02 PM" src="https://user-images.githubusercontent.com/6225588/160675293-02b1443e-df9c-4b6b-97d9-6f89f54ce0bf.png">

**Comment by Sytten** [comment]
Hum did you investigate if there is a way to batch remove shortcuts?
I would say a third option would be to fork the editor and add said batch function (and try to upstream it).

**Comment by Corb3nik** [comment]
There's an official API for shortcut edits now
https://github.com/microsoft/monaco-editor/issues/102#issuecomment-1282897640
