### ISSUE TITLE
Add scope to intercept

### ISSUE THREAD

**Issue by Sytten** [caido/caido#187]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

[Original discussion](https://discord.com/channels/843915806748180492/902965396397752370/957133376983294022)

Allow a user to use a scope for the forward.

**Questions:** 
- What should happen to out of scope?
    1. Forward automatically (then what happens if we introduce multiple forward views)
    2. Keep in pending mode

**Comment by cwinhall2** [comment]
Adding to the comment above, it would also be useful to be able to build a rule on out of scope traffic. For example: I not only don't want to see out of scope traffic in the intercept but I would like to be able to choose which to forward automatically versus which to drop automatically.

**Comment by Sytten** [comment]
In the coming release we will add the scope and anything out of scope will be forwarded, here is the issue for filter https://github.com/caido/caido/issues/580 @cwinhall2
