### ISSUE TITLE
Package Caido in a Desktop application

### ISSUE THREAD

**Issue by Sytten** [caido/caido#205]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

We should distribute Caido in an electron/tauri application for people that prefer to have a separate window for the tool.
This is also much better for beginners that might not be familiar with the command line.

**Comment by Corb3nik** [comment]
Closed via #19
