### ISSUE TITLE
Changes to a replay are lost if the request is in-flight

### ISSUE THREAD

**Issue by wbowling** [caido/caido#224]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description
After sending a replay, any changes made to the request are lost when the response comes in.

### How to reproduce

1. Send a request to the replays tab
2. Send the replay
3. Before the response comes back, make some changes
4. The changes are replaced when the response comes back

### Environment & setup

OS: macOS
OS version: 12.2
Caido version: 0.15.0-13a2d7e6

**Comment by wbowling** [comment]
This was only really an issue when working with a very slow/flakey server, after waiting a bit I often found that I wanted to change the request but if I didn't hit cancel the changes were replaced if the response finally came back.

A potential solution is to have a new "pending" request page which gets activated anytime you edit a request. This would allow you to edit an in-flight request (it would go into the pending mode) and if the response comes in it just gets added to the list like normal

**Comment by Corb3nik** [comment]
Closed by mistake, this isn't fixed yet.

**Comment by Corb3nik** [comment]
This is fixed as of v0.40
