### ISSUE TITLE
Support mixed content in formatting

### ISSUE THREAD

**Issue by Sytten** [caido/caido#226]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Currently we support only one content. We probably want users to be able to create formatting pipelines that can detect and format part of a request/response.

**Comment by Corb3nik** [comment]
This seems to be covered by workflows now
