### ISSUE TITLE
Change intercept entry row colors

### ISSUE THREAD

**Issue by Corb3nik** [caido/caido#234]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Allow users to `Right-Click -> Change row color` on various table rows.

### Use cases

This allows users to bookmark interesting requests visually.

Vaguely related to #214

**Comment by Sytten** [comment]
Related to https://github.com/caido/caido/issues/372

**Comment by lauritzh** [comment]
+1, would be also useful to programatically highlight certain requests of interest (let's say SSO request like the [EsPReSSO Burp Extension](https://portswigger.net/bappstore/e1d08d4ab1ea4c17be3431d7d2b20b30) does).
