### ISSUE TITLE
Caido authentication and access control

### ISSUE THREAD

**Issue by Sytten** [caido/caido#240]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

We will transition from licenses to accounts. This requires the user to be able to login in their instance.
Once this is doable, we can implement access control on instances and sharing via the portal.

### Use cases

- Exposing Caido to the internet safely
- Sharing access to Caido instances easily
- Detach the machine from the user (machines are free, capabilities are tied to the account)

**Comment by Corb3nik** [comment]
Closed via https://github.com/caido/proxy-frontend/pull/665 and https://github.com/caido/proxy-backend/pull/614
