### ISSUE TITLE
Add URL in logs for TLS errors

### ISSUE THREAD

**Issue by dee-see** [caido/caido#242]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

TLS errors don't mention what domain caused the error which can make it a bit hard to figure out what's happening.

### Use cases

I'm working with Android apps and often see errors like these because of certificate pinning. More detailed error messages would help me track down what pinning bypass isn't working (and also if that request is relevant to begin with, if it's only the tracking shit that's broken I don't care)

```
19:54:27 [ERROR] TLS alert received: AlertMessagePayload {
    level: Fatal,
    description: CertificateUnknown,
}
19:54:27 [ERROR] Msg: received fatal alert: CertificateUnknown, Meta: Metadata { request_id: 16a86709-b82c-471a-8faa-10cd2ed5a7ae }
```

**Comment by dee-see** [comment]
@Sytten feel free to rename to "enable debug logs" if that's what you're going to do to solve this problem

**Comment by Sytten** [comment]
Keeping the issue as is, but opened another one to track debug logs. To be closed in next release.
