### ISSUE TITLE
Enable debug logs

### ISSUE THREAD

**Issue by Sytten** [caido/caido#243]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Allow users to see debug logs on demand.

### Use cases

- Allow to debug #242

**Comment by dee-see** [comment]
Hey @Sytten, I know it's been a while but I was trying to debug certificate pinning and even with the `--debug` switch I get no details about `CertificateUnknown` errors

```
18:07:49 [ERROR] TLS alert received: AlertMessagePayload {
    level: Fatal,
    description: CertificateUnknown,
}
18:07:49 [ERROR] Msg: received fatal alert: CertificateUnknown, Meta: Metadata { request_id: 76842ffe-5603-42d6-b83d-336f95e87abe, target: None }
```

and this query returns no results

```graphql
{
  request(id: "76842ffe-5603-42d6-b83d-336f95e87abe") {
    host
  }
}
```

**Comment by Sytten** [comment]
Hum I will open another issue for debugging certificate pinning. I would have thought you would know the domain in the logs :/
