### ISSUE TITLE
Burp Collaborator equivalent / interactsh integration

### ISSUE THREAD

**Issue by Corb3nik** [caido/caido#245]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Look into making a Burp collaborator equivalent. Maybe an integration with https://github.com/projectdiscovery/interactsh ?

**Comment by sw33tLie** [comment]
This is available now in evenbetter: https://github.com/bebiksior/EvenBetter

**Comment by Corb3nik** [comment]
This now has its own plugin :)

https://github.com/caido-community/quickssrf
