### ISSUE TITLE
Variable Store

### ISSUE THREAD

**Issue by Corb3nik** [caido/caido#247]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Add a variable store that can be auto inserted in various replay/automate requests. 

Users' could setup a variable called `$API_KEY: "my-api-key"`, and use that variable in replay sessions such as

```
GET / HTTP/1.1
Host: github.com
Authorization: Bearer ${API_KEY}
```

### Use cases

Sometimes users' have short-lived API keys you'll want to use in multiple replay requests. When these keys expire, users have to update all of their replay sessions with a new key. This can be tedious.

Having a variable store would allow users to only need to overwrite the store with the new key.

**Comment by Sytten** [comment]
I do think we need that sooner rather than later
