### ISSUE TITLE
Allow replay to follow redirects

### ISSUE THREAD

**Issue by Sytten** [caido/caido#25]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Right now the replay doesn't follow the redirects and that is a good thing, but it would be nice if it was possible to let it follow them with a setting. Preferably it would also record the 302 response (this might not be possible based on current backend design).

**Comment by hakluke** [comment]
I would love to be able to walk through the chain of requests forward and back, cycling through each redirect.
