### ISSUE TITLE
Include pre-configured browser

### ISSUE THREAD

**Issue by jrozner** [caido/caido#255]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Burp provides an included version of Chrome that is pre-configured with proxy settings and some reasonable changes to the default behavior for testing. This is nice because everything just works out of the box, it doesn't pollute my normal browser profile with testing, and there is no manual management of proxy settings which is sort of a pain in the ass to do with Chrome.

### Use cases

All?

**Comment by Corb3nik** [comment]
We could leverage something like https://httptoolkit.com/

![](https://cdn.discordapp.com/attachments/897574971885359174/1096537714830094336/image.png)

**Comment by Sytten** [comment]
In the meantime, it is easy to emulate that behaviour yourself with a few flags when launching chromium. See:
- https://www.stevenrombauts.be/2017/04/how-to-disable-chrome-security-checks/
- https://peter.sh/experiments/chromium-command-line-switche
