### ISSUE TITLE
Filter rules overflow issue

### ISSUE THREAD

**Issue by dee-see** [caido/caido#263]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

Filter rules overflow under the right panel and the `X` kind of floats around (which is more convenient than a hidden `X` I would say)

I would suggest either forcing a wrap-around or having a `...` and show the full thing on hover

### How to reproduce

![image](https://user-images.githubusercontent.com/7252342/183167717-73962e64-3c80-411f-9259-a7394565a73c.png)

### Environment & setup

OS: Arch linux
OS version: 5.18.15-arch1-1
Caido version: 0.17.0

**Comment by Corb3nik** [comment]
Forced a wrap-around and made the well components scrollable
<img width="364" alt="Screen Shot 2022-08-09 at 2 58 39 PM" src="https://user-images.githubusercontent.com/6225588/183740081-d6062561-775b-41e7-9b0d-c1cdd331f996.png">

**Comment by Corb3nik** [comment]
<img width="557" alt="Screen Shot 2022-08-09 at 4 06 49 PM" src="https://user-images.githubusercontent.com/6225588/183750948-ae85bf8d-0a61-421d-b2ef-5d4ca810436e.png">

Went with the wrap-around solution for now :) There's probably a more elegant solution to this, but at least now you'll be able to see entire filters properly.

**Comment by dee-see** [comment]
Works for me! Thanks for the quick fix

Le mar. 9 août 2022, 13 h 14, Ian Bouchard ***@***.***> a
écrit :
