### ISSUE TITLE
Add a "dirty" indicator for the tamper rule

### ISSUE THREAD

**Issue by Sytten** [caido/caido#273]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Right now it's not obvious if the rule as been saved, it would be better to activate/deactivate the save button on change/save or add an indicator similar to the scope.

**Comment by Corb3nik** [comment]
Closed via https://github.com/caido/proxy-frontend/pull/691
