### ISSUE TITLE
Add different ways to load wordlists in Automate

### ISSUE THREAD

**Issue by sw33tLie** [caido/caido#275]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

It'd be great to have different ways to load wordlists in Automate, either by selecting files locally stored on the server running caido or via URL.

### Use cases

This would help people with slow upload speeds that host caido on their VPS.

**Comment by Sytten** [comment]
See the linked issue!
