### ISSUE TITLE
Add filters on automate requests

### ISSUE THREAD

**Issue by Sytten** [caido/caido#279]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

We should add similar filters as those on intercept to the automate requests.

**Comment by Corb3nik** [comment]
Closing this. Duplicate of https://github.com/caido/caido/issues/219
