### ISSUE TITLE
Add JSON pretty in forward & replay view

### ISSUE THREAD

**Issue by Corb3nik** [caido/caido#294]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Add prettifying in forward view

**Comment by Rhynorater** [comment]
And in replay, please!

**Comment by Corb3nik** [comment]
Currently, this is possible using `Right-click -> Format as JSON`

Since forward and replay are writable views, I'm not sure what the expected behavior should be with a "Pretty view".

### Burp Suite behavior
IIRC, Burp Suite shows a prettified version without actually modifying the contents.

Therefore, if a replay's pretty view content looks like
```JSON
{
  "a": "b"
}
```

Sending the request might still actually send `{"a":"b"}`.

I don't know if that's the best behavior for this feature.


### Ideas

Since the replay / forward are writable views, I find the behavior should be closer to what IDEs do.

Ideas so far:
- A replay option to format automatically on send
