### ISSUE TITLE
Ability to de-select a scope

### ISSUE THREAD

**Issue by Rhynorater** [caido/caido#301]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

When utilizing the scope interface, it would be great to be able to `deselect` a scope and revert back to all requests being shown. Currently, the only way to do this is to delete the scope or create a new scope called `all` which doesn't have any scope restrictions. Or perhaps `All` could be a default scope which cannot be changed or removed.

### Use cases

When a user is wanting to focus on a specific scope, they may narrow down the in-scope assets only to realize afterward that they need to go back to seeing all requests and some piece of functionality it is missing.

**Comment by Corb3nik** [comment]
Currently working on improving the scope UI, so this issue should be resolved soon 👍 
<img width="1680" alt="Screenshot 2022-11-01 at 12 55 40 PM" src="https://user-images.githubusercontent.com/6225588/199291365-57dfe6dd-91e1-484b-a11f-91aef5e36295.png">

**Comment by Rhynorater** [comment]
Sweet! Looking forward to it.

**Comment by Corb3nik** [comment]
Closed via https://github.com/caido/proxy-frontend/pull/698
