### ISSUE TITLE
When Forwarding queued requests, the next request should be auto-selected

### ISSUE THREAD

**Issue by Rhynorater** [caido/caido#302]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

When forwarding through requests, the next request should be selected.

https://www.loom.com/share/b907f649bf474bc4a64d98a50581a081

### Use cases

Users would use this to quickly forward requests.

**Comment by Corb3nik** [comment]
Closed via caido/proxy-frontend#729
