### ISSUE TITLE
Scroll through requests in Intercept with Arrows

### ISSUE THREAD

**Issue by Rhynorater** [caido/caido#305]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

I would like to be able to scroll through the requests in Intercept using the up and down keys.

### Use cases

I will use this to scroll through requests quickly without having to use the mouse.

**Comment by Sytten** [comment]
Similar issue as https://github.com/caido/caido/issues/91
