### ISSUE TITLE
Desktop application logs

### ISSUE THREAD

**Issue by Sytten** [caido/caido#311]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Currently we don't have a good strategy for logs in the desktop application. They are mostly dumped in the void right now unless you open the desktop application from a terminal. We should store them somewhere and maybe make them accessible to the frontend.

### Use cases

Mainly debugging.

**Comment by Corb3nik** [comment]
Closed in v0.35.0
