### ISSUE TITLE
Conditional Match & Replace

### ISSUE THREAD

**Issue by Rhynorater** [caido/caido#313]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

One of the features that could set Caido aside as the go-to web proxy tool would be the ability to do conditional match & replace. For example, if I only want to replace `"admin":false` to `"admin":true` in requests that have `/api/profile` in the path. 

This would really be a game-changer.

**Comment by Sytten** [comment]
User suggestion:
```
- Ruleset for Tampering, example:

Action: Drop request
Strategy: Request header
Match: Host: %.example.com 
OR 
Strategy: Request header
Match: example.com 
AND NOT 
Strategy: Request header
Match: User-Agent: foobar
```

**Comment by Rhynorater** [comment]
```
would love a way to select text from the HTTP History tab and be able to right click and select "Match&Replace" and have that text be pre-loaded into a new rule as the match.
```
