### ISSUE TITLE
Export requests and responses from history search results

### ISSUE THREAD

**Issue by Pheelbert** [caido/caido#322]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

After performing a search in the history tab, an export button would allow the user to save all the requests and responses to disk. Many formats could be useful: json, fff-style greppable format (https://github.com/tomnomnom/fff), csv.

**Comment by Corb3nik** [comment]
Closed via https://github.com/caido/proxy-frontend/pull/828
