### ISSUE TITLE
Copy URL doesn't work consistently

### ISSUE THREAD

**Issue by Corb3nik** [caido/caido#323]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

The right click -> "Copy to URL" option doesn't work for linux desktop users.

Bug needs investigation, but ideas of what it could be:
- Tauri-related issue for linux 
- Request parsing issue preventing only certain requests from being copied properly.

Bug occurs on `Ubuntu Gnome 20.04` with Linux desktop app

Has also been reproduced on Linux + Firefox

**Comment by dee-see** [comment]
Reproduced in the web version 0.22.1. Arch Linux, Firefox and chromium both don't work. I can't copy any URLs in any project

**Comment by carboncrystal** [comment]
Ubuntu 22.04 installed Caido as .deb confirmed as bug "the copy URL". It doesn't work!

**Comment by Corb3nik** [comment]
I believe this might be related to https://stackoverflow.com/a/51823007

@dee-see @carboncrystal Can you still reproduce this bug?

If so, what IP are you using to connect to Caido? 

When I connect to a Caido instance on 127.0.0.1, it works fine. But if I connect to a Caido instance on another IP, `copy URL` will fail.

Just want to be sure I've pinpointed the correct issue here.

**Comment by dee-see** [comment]
@Corb3nik Indeed! I usually access Caido on 0.0.0.0 but trying on 127.0.0.1 works. :+1:
