### ISSUE TITLE
Linux desktop requires libc >=2.32

### ISSUE THREAD

**Issue by Sytten** [caido/caido#342]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

The linux desktop build requires libc >=2.32 while ubuntu 20 is still a libc 2.31. This is due to our build machine that upgraded to the latest OS.

**Comment by gruel-coveo** [comment]
Hello @Sytten  ! 

Does the fix involve making it compatible with Ubuntu 20 ? Still getting this error in the latest v0.22.1 Desktop release: 

`caido: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.33 not found (required by caido)`
`caido: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.34 not found (required by caido)`
`caido: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.32 not found (required by caido)`


Running Ubuntu 20.04

**Comment by Sytten** [comment]
We messed up our latest release it seems, re-opening. I am building a fixed version right now.

**Comment by Sytten** [comment]
Fixed build: https://storage.googleapis.com/caido-releases/internal/caido-desktop-linux-main-e481b8f1.deb

**Comment by Sytten** [comment]
Fixed build: https://storage.googleapis.com/caido-releases/internal/caido-desktop-linux-v0.22.1-7e0bcca8.deb

**Comment by Sytten** [comment]
Fixed build pipeline
