### ISSUE TITLE
Issue with Installation Caido LINUX Desktop(Deb)

### ISSUE THREAD

**Issue by Crypto-Breaker** [caido/caido#344]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description
when i am trying to install Caido LINUX Desktop(Deb) (Caido version: 0.22.1) unable to install saying that the caido requires libc library which is already present in my system
following is the output i am receiving
caido: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by caido)
caido: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by caido)
caido: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by caido)
### How to reproduce
just try to install the deb file in ubuntu 20.04.5 using 
dpkg -i cadio.deb

### Environment & setup

OS: Debian
Flavour:Ubuntu 20.04.5 LTS
OS Type:64bit
GNOME Version :3.36.8
Caido version: 0.22.1

**Comment by Corb3nik** [comment]
Just got another report for this a few minutes ago :) We're working on deploying a new build to fix this in the next hour!

**Comment by Sytten** [comment]
Fixed build: https://storage.googleapis.com/caido-releases/internal/caido-desktop-linux-main-e481b8f1.deb
Closing in favour of #342
