### ISSUE TITLE
Support offline mode

### ISSUE THREAD

**Issue by Sytten** [caido/caido#347]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Right now the tool can be used 7 days offline after login, but it is not really clear. We need a proper offline mode & stealth so no network requests are made.

EDIT: Currently the 7 days isn't really working anyway due to long timeouts if you have a network but no internet access.

### Use cases

- On-site pentests

**Comment by Sytten** [comment]
Two proposal: 
- After the initial login, request offline access in the app for up to X days (X can't be more that the remainder of your subscription)
- Do the login flow on your internet-connected computer and copy the result into caido fully offline (you would not even have to request for first time access), the login would still be valid for Y days (currently 7 but can be changed)

**Comment by Corb3nik** [comment]
Closed via https://github.com/caido/proxy-frontend/pull/1753

**Comment by Sytten** [comment]
We support partial offline mode, full offline mode will come later
