### ISSUE TITLE
History and intercept tabs are confusing

### ISSUE THREAD

**Issue by Sytten** [caido/caido#349]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

A lot of users reported being confused by the differences between the two tabs.
We might want to merge the two and allow for "tabs" to be created with filters (so by default you would get an intercept tab for intercepted requests).

**Comment by Corb3nik** [comment]
Closing this. Haven't heard any complaints since the switch (Intercept -> HTTP History, History -> Search)
