### ISSUE TITLE
Intercept/history table sometimes misbehave

### ISSUE THREAD

**Issue by Sytten** [caido/caido#351]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

Sometimes the requests are all stacked on top of each other. Resizing columns has weird behaviours. Sorting not working when clicking on headers.

### Environment & setup

Caido version: 0.22.1

**Comment by Corb3nik** [comment]
There are three issues here. Managed to fix one of them
- [x] Sometimes the requests are all stacked on top of each other.
- [ ] Resizing columns has weird behaviours. 
- [ ] Sorting not working when clicking on headers.



I believe the sorting issue has to do with the fact that some fields are currently unsortable.

We can't sort by query, state, or response length in the intercept table yet.

<img width="307" alt="Screenshot 2023-02-21 at 6 08 03 PM" src="https://user-images.githubusercontent.com/6225588/220479221-82610a34-2325-4c72-88d0-7df1a49d3785.png">
