### ISSUE TITLE
Error on stale date should be better

### ISSUE THREAD

**Issue by Sytten** [caido/caido#352]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

Requests from our cloud are signed with the date of the server. We currently only allow a difference of 5m between that date and the computer date. This is sometimes causing issues to users that have a wrong date. We should increase that cutoff and communicate to the user this error.

**Comment by Corb3nik** [comment]
Closing in favor of #616
