### ISSUE TITLE
Slow UI on Linux Desktop

### ISSUE THREAD

**Issue by Sytten** [caido/caido#358]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

The desktop version of Caido uses the OS native webview system. On Linux, this happens to be `webkit2gtk` which is not the fastest in town. We suggest users experiencing slow down in the app to switch to their browser for the time being or try to upgrade their version of `webkit2gtk`.

### Environment & setup

OS: Linux
Version: webkitgtk-2.38

**Comment by Corb3nik** [comment]
Closed via https://github.com/caido/proxy-desktop/pull/185
