### ISSUE TITLE
Importing List of in Scope Domains

### ISSUE THREAD

**Issue by mattzamat** [caido/caido#362]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Hey there,

Apologies if this has been already asked or addressed; I did not see it in the list of historical issues. I think it would be really helpful to import a list of line separated domains (URL or regex) into the scope tab.

### Use cases

Projects with very wide scope, or any project that has a lot of domains in scope.

**Comment by Corb3nik** [comment]
This is now available as of v0.32.1
