### ISSUE TITLE
Upload Caido to the AUR (Arch Linux User Repository) 

### ISSUE THREAD

**Issue by ZeddGrayhem** [caido/caido#365]
There's currently no easy way to install Caido for Arch users. Outside of just installing the debian release which I've noticed causes a few things to stop working.

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

**Comment by Sytten** [comment]
We have no experience related to distribution on Arch linux, so any guide / directions you can point us toward would be much appreciated 👍

**Comment by ZeddGrayhem** [comment]
I'm not extremely familiar with the process, but afaik it's quite straight forward. Arch wiki has a pretty clear, and well written guide on how to create and distribute a package.

https://wiki.archlinux.org/title/Creating_packages

**Comment by apehex** [comment]
I'm in the same spot as @ZeddGrayhem !
I never wrapped a package for Arch, but this is exactly the time to learn so I'd be willing to help :D

**Comment by Sytten** [comment]
There are a few things to consider:
- Do we want to package the CLI and/or the desktop application
- The tauri bundler has an issue and PR tracking the pacman bundling: https://github.com/tauri-apps/tauri/issues/3728
- The CLI can be packaged from the binary on release similar to what we do here: https://github.com/caido/caido/blob/main/.github/workflows/docker-build.yml

I would suggest we start with the CLI as a github action that runs on release in this repository. I don't expect I will have time to craft myself soon, so feel free to give it a shot @apehex.

For the desktop application, I am more inclined to wait for the tauri bundler to be ready so I can just add it to our build pipeline, but we can also do something similar to the CLI in the distribution pipeline.

**Comment by apehex** [comment]
Sorry @Sytten !! I've been swept away by other projects, I don't use web proxies anymore ^^'
Still, I've seen that the standalone binary actually works out of the box on Archlinux !
Did you have the same experience @ZeddGrayhem ?

**Comment by Sytten** [comment]
All good, we will take care of it. Thanks for confirming ♥

**Comment by Sytten** [comment]
There is now an unofficial package https://aur.archlinux.org/packages/caido-desktop

**Comment by rew1nter** [comment]
This unofficial package doesn't work for me at least. Shows a blank white screen only.

**Comment by Sytten** [comment]
Yeah its likely the gtk webview bug as https://github.com/caido/caido/issues/406, we still have not gotten around to finding a fix for it. It's a bug in the engine level.

**Comment by cocoonkid** [comment]
The AUR packages work great.

But I can confirm from my side that I had 
`JSC_useDFGJIT=0` in the first release enabled (but did not really use it until now).


The latest version 0.29.x works great and I removed` JSC_useDFGJIT=0`.

No issues at all. LMK if any additional informations regarding my system is helpful.

electron --version
v25.9.3

uname -a
Linux arch 6.5.9-zen2-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 26 Oct 2023 00:51:53 +0000 x86_64 GNU/Linux

**Comment by Sytten** [comment]
Interesting, I will have to take a look. @cocoonkid could you let me know the version of webkit gtk you have (`apt list | grep webkit`)

**Comment by meme-lord** [comment]
The commands `caido` and `JSC_useDFGJIT=0 caido` show blank window for me with this error output:
```
src/nv_gbm.c:288: GBM-DRV error (nv_gbm_create_device_native): nv_common_gbm_create_device failed (ret=-1)

src/nv_gbm.c:288: GBM-DRV error (nv_gbm_create_device_native): nv_common_gbm_create_device failed (ret=-1)

KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 800x600: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 800x600: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 800x600: Permission denied
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1
```
I was able to get it working with this comand:
```bash
WEBKIT_DISABLE_DMABUF_RENDERER=1 caido
```
Which I got from [here](https://github.com/elementary/browser/discussions/104)

**Comment by Sytten** [comment]
Thats done now: https://aur.archlinux.org/packages?O=0&K=caido
