### ISSUE TITLE
Out of scope seems to not be applied to some requests

### ISSUE THREAD

**Issue by Sytten** [caido/caido#368]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

It was reported that some domains explicitly excluded in out of scope still seem to appear.
Do we actually refresh the table when the scope is changed? @Corb3nik  

### How to reproduce

See #caido-ayoub channel

**Comment by Corb3nik** [comment]
Closing this as we haven't heard any other users have this issue in a while.
