### ISSUE TITLE
Replay session navigation counter is wrong

### ISSUE THREAD

**Issue by Sytten** [caido/caido#374]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

`Replay history seems to be bugged, if you have 1 in your history and issue another request it will show 2/3, 4/5, 6/7 etc. And it won't correct itself until you close and reopen the replay session.`

### How to reproduce

See description

### Environment & setup

OS: ?
OS version: ?
Caido version: 0.22.1

**Comment by Corb3nik** [comment]
Closing this, I've never been able to reproduce this issue.
