### ISSUE TITLE
Shifted formatting in Automate

### ISSUE THREAD

**Issue by nonsleepr** [caido/caido#378]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

In Automate, when multiple insertion points are marked, each insertion point gets a yellow box drawn around it, that box shifts the text.
When the token is selected or has the cursor on it, the editor highlights same tokens around. That highlighting doesn't consider the text being shifted because of mark boxes:

![image](https://user-images.githubusercontent.com/2337602/218145926-aaa59a27-179b-4fa8-b828-e87e52052143.png)

### How to reproduce

1. Insert the following content into the editor:
```http
POST /fuzz HTTP/1.1
Host: www.redacted.com
Content-Length: 240

func():func(blue):func(blue,true):func(90):func(90,90):func(90,90,90):func(90,90,90,90):func('blue'):func("blue"):func("blue",90)
```
2. Mark all occurrences of `func`
3. Place a cursor on one of the `func` tokens
4. Observe misaligned highlights.

### Environment & setup

OS: Windows
OS version: 11
Caido version: 0.22.1

**Comment by Corb3nik** [comment]
This issue should be fixed with the new code editor implementation on v0.23.1. Feel free to re-open if the bug still exists!
