### ISSUE TITLE
Ability to Define Scope

### ISSUE THREAD

**Issue by Rhynorater** [caido/caido#38]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

It would be great if we could have a place where we could define regex which would limit the hosts displayed on the left-hand side of the `Overview` tab. This would allow for all the junk to be deleted and focus on assets that are relevant to the target. 

### Use cases

It would be used anytime someone is doing a target assessment and doesn't want to have other tabs or irrelevant 3rd parties clogging up screen space.

**Comment by Sytten** [comment]
I see two potential features here, would you prefer that the engine record all the connections and then filter them when you query OR that it just doesn't record the data for hosts that don't match the regex?

**Comment by Rhynorater** [comment]
I think there should be an option for both. But for the beta, perhaps one that just allows filtering, but keeps all data in the record. This is the most helpful for professional hackers anyway because often times it is possible that we may need to go back and assess an asset's presence among multiple projects.

Also, I might add, this is 100% the biggest blocker for me to use this app right now. If we could get this out of the way, I would potentially start using Caido as my main tool.

**Comment by Rhynorater** [comment]
Super hype about this! Can't wait for the next release!
