### ISSUE TITLE
Browser version is wrong

### ISSUE THREAD

**Issue by Sytten** [caido/caido#380]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

Should display 107, but displays the old 88 version. That will cause issues with the update functionality but we can do a migration to avoid it.

**Comment by Corb3nik** [comment]
Closed via https://github.com/caido/caido/issues/380
