### ISSUE TITLE
Submit Caido to the AUR package repository of Archlinux

### ISSUE THREAD

**Issue by apehex** [caido/caido#392]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

I propose to wrap the Caido sources into an Archlinux / Blackarch package.
[AUR](https://wiki.archlinux.org/title/Arch_User_Repository) is the community package repository for Archlinux.

### Use cases

KISS with Archlinux users <3

**Comment by Sytten** [comment]
Is this the same https://github.com/caido/caido/issues/365? @apehex 
I didn't have time to look into arch distribution yet

**Comment by apehex** [comment]
Oh damn sorry ! Yes it's exactly it, I'm closing the issue then :)
