### ISSUE TITLE
Add ChatGPT integration

### ISSUE THREAD

**Issue by Sytten** [caido/caido#395]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

We want to allow our users to leverage ChatGPT directly in Caido if they want to.

We will most likely use the hosted services of OpenAI and self-host down the line. This has some privacy implications that we need to inform our users about since data will be sent to this third party if and when the user decides to use it.

### Use cases

- Select anything in the app, right-click explain and get an answer

**Comment by nonsleepr** [comment]
Can't that use case be accomplished by a third-party browser extension?

**Comment by Sytten** [comment]
Maybe but not in the desktop app and there is a possibility to add more use cases later like helping building of reports.

We will also be able to offer private instances down the line for Caido instead of people using the public instances.
