### ISSUE TITLE
I like it very much, I hope to make some suggestions.

### ISSUE THREAD

**Issue by mastersir-lab** [caido/caido#399]
I am a user from China, I like this tool very much, including its fluency and practicality. I always look forward to the tool becoming more perfect and provide some suggestions for adoption.
1、Can you set the language of multiple countries？Like Chinese。
2、We test the site which contains a lot of Chinese, tools in the display of Chinese will be garbled。
3、Login authentication is cumbersome, can you provide a long-term local ticket to verify login information when using the software?
Thank you very much for your results and continued support！

**Comment by Corb3nik** [comment]
Hi @mastersir-lab!

Thanks for the feedback. Let's break down your suggestions:

>  1、Can you set the language of multiple countries？Like Chinese。

Not at the moment, but we do have an issue opened for this https://github.com/caido/caido/issues/348 (please upvote 👍 it so we can track interest)

>  2、We test the site which contains a lot of Chinese, tools in the display of Chinese will be garbled。

We're finishing up a bug fix for this. It should be available in the next release. Here's a screenshot of the fix supporting Japanese characters :)

<img width="657" alt="Screenshot 2023-03-23 at 3 04 44 PM" src="https://user-images.githubusercontent.com/6225588/227321569-13f9d038-34f2-4eac-b66f-863001b08a66.png">

>  3、Login authentication is cumbersome, can you provide a long-term local ticket to verify login information when using the software?

Normally, when you use the desktop application, you only have to login once. If you use the browser, you will stay logged in as long as you don't delete your cookies. What was the issue you were having with login right now?

**Comment by Sytten** [comment]
@mastersir-lab just checking if you had all the answers you needed?
Closing for now, we can open more specific issues for each point
