### ISSUE TITLE
Ctrl-Z and Ctrl-Y in Replay

### ISSUE THREAD

**Issue by Rhynorater** [caido/caido#40]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

It is very useful when testing to be able to quickly cut something out of a text area, submit the request, and then CTRL-Z it if it doesn't work. Currently, we are unable to CTRL-Z text within the replay panel.

**Comment by Sytten** [comment]
Currently each request adds to the linear history of the replay tab ("session") so that you can go back and forth with the arrows. The Ctrl-Z seems a bit different, this would like:
1. Send request 1
2. Send request 2
3. CTRL-Z => back to request 1
4. Send request 3, view moved to request 3
5. CTRL-Z => back to request 1
Would this be confusing since the history is linear? 
Should we make the history of replay not linear? We could add a visual timeline of the replay tab/session.

**Comment by Rhynorater** [comment]
Hmmm, I would say that each time the request is sent that should create a new state for the request as a whole. Those states can be cycled through via the forwards and back buttons. Then, within those states, there is the ability to Ctrl-Z and Ctrl-Y. For example:

1. Send request 1
2. Modify, send request 2 (request 2 inherits request 1's Ctrl-Z History)
3. Ctrl-Z (so now it looks like request 1), modify again, send request 3
4. Press back button (looks like request 2, even though we've Ctrl-Z'ed that because that was what it looked like when we sent the request)


Does that make sense? Would love to see some input from other hackers here @Corb3nik @dee-see

**Comment by Corb3nik** [comment]
Yeah that makes sense. If I understand correctly, the idea is that we'd want to keep track of modifications. We're not using Ctrl+Z & Ctrl+Y to navigate between requests in a replay tab.

An example where the undo shouldnt't work would be:
1. Send request 1
2. Send request 2 (without modifications)

Doing Ctrl+Z _shouldn't_ do anything here. We'd still be on request 2.

**Comment by Rhynorater** [comment]
Yep, that's exactly right! Let me know if I can help with anything else for this issue!
