### ISSUE TITLE
Blank page on Kali Linux in Desktop app

### ISSUE THREAD

**Issue by Corb3nik** [caido/caido#406]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

The desktop app displays a blank screen when attempting to connect to an instance.

This is the error message shown in the browser inspector
```
[Error] Unhandled Promise Rejection: TypeError: e.toString().match is not a function. (In 'e.toString().match(/^\s*function (\w+)/)', 'e.toString().match' is undefined)
```

### Environment & setup

No LSB modules are available.
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2023.1
Codename:       kali-rolling

**Comment by DanielKobjolke** [comment]
Workaround till fix: Launch Instance and go manual to IP:PORT (ex:127.0.0.1:8080) in Browser. Just for everyone stuck on this.

**Comment by Sytten** [comment]
We will stop shipping the deb version of Caido Desktop since this seems to be an issue with more recent versions of webkit over which we have no control over. See https://bugs.webkit.org/show_bug.cgi?id=256663 if you are interested.

**Comment by wuyudi** [comment]
use

```
JSC_useDFGJIT=0 caido
```

and it works well.

**Comment by Sytten** [comment]
Yes there is a bug in one of the Just in time compiler (JIT), but we cant expect user to set that. I believe we will have to switch to electron, TaurI is just not good enough and causes us too much trouble.

**Comment by wuyudi** [comment]
Actually what I did now is to sed the desktop file. But not good, since the users may use cli to launch it.

```sh
sed -i "s/Exec=caido/Exec=JSC_useDFGJIT=0 caido/" $pkgdir/usr/share/applications/*.desktop
```

as for the package, I found that Tauri has

https://tauri.app/v1/api/config/#debconfig

which may be helpful.

> But Tauri is troublesome..

**Comment by Sytten** [comment]
Yeah that could be an option, but disabling DFG JIT will slow the app down even more and its already very slow compared to other modern browsers.

The problem with Tauri from our side is mostly that it explodes the number of potential browsers we have to test on since we can't assume it is going to use a recent version. On my mac it uses a 5 years old safari version, on linux it depends on the distro, etc. This is fast becoming not viable for our small team of 3 to deal with.

**Comment by cocoonkid** [comment]
I disabled it and works like charm.
https://github.com/caido/caido/issues/365#issuecomment-1793375750

**Comment by Sytten** [comment]
I believe this is fixed in updated versions of webkit now? We will renable deb releases so users can tell us.

**Comment by Corb3nik** [comment]
Closed via https://github.com/caido/proxy-desktop/pull/185
