### ISSUE TITLE
Transition from % to *

### ISSUE THREAD

**Issue by Sytten** [caido/caido#408]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Its a recurring complaint that `%` is not obvious, users are used to `*`. Though for existing users we will want to keep supporting the % (we will probably need a way to escape the %).

**Comment by Corb3nik** [comment]
Duplicate of https://github.com/caido/caido/issues/544
