### ISSUE TITLE
Verify if content-length option in replay is correct

### ISSUE THREAD

**Issue by Sytten** [caido/caido#410]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

The backend is still the same around that section, so we just need to verify if the option is properly sent to the backend. User reported it might not be anymore on discord.

**Comment by kmskrishna** [comment]
If the content-length header is not set, and the `update-content-length` option is enabled in Caido, it should automatically create the header and then update it.

Right now, it updates the header if it is present, but it should also create and update it if the `update-content-length` is enabled
