### ISSUE TITLE
Add option to temporarily deactivate filters

### ISSUE THREAD

**Issue by rew1nter** [caido/caido#414]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Some *contains*/*not contains* filters are long and you often have to deactivate them for a temporary time during tests.
To do that you currently have to recreate the filter every time. Having a temporary deactivation system like a tick mark or a drag and drop to an *inactive filters box* would be nice. 

### Use cases

Recreating the mostly used filters will take even more time when you introduce regexes. So it'll be time-saving to have a deactivation option.

**Comment by rew1nter** [comment]
Consider a right click option too if you'll be implementing this

**Comment by Sytten** [comment]
We will be reworking the filtering heavily soonish, I will make sure to integrate this idea in the redesign. Thanks!
