### ISSUE TITLE
Add a way to export the history,sitemap and the requests and responses into files

### ISSUE THREAD

**Issue by hashem-mo** [caido/caido#420]
### Description
implement a way to export the history,sitemap and requests and respones into txt or json files

### Use cases

it will help in enganging other tools and some investigations processes

**Comment by Corb3nik** [comment]
Hi @hashem-mo!

We currently have an export feature in the top left of these pages. You can export as CSV and JSON.

Is their anything in particular that's missing with that feature?

<img width="892" alt="Screenshot 2023-05-13 at 11 03 01 AM" src="https://github.com/caido/caido/assets/6225588/ad203bf8-69c5-43d5-9c4e-db884e7a96f5">

**Comment by hashem-mo** [comment]
Oh thanks, I found out i was using old version
