### ISSUE TITLE
Add a comparer between texts and requests

### ISSUE THREAD

**Issue by hashem-mo** [caido/caido#424]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Add a comparer tap that allows you to compare texts,it will help in analyzing tokens and reverse engineer it

### Use cases
Compare strings,tokens

**Comment by Sytten** [comment]
I will close in favour of https://github.com/caido/caido/issues/164
Let me know if that is not the same
