### ISSUE TITLE
Intercept sorting issues

### ISSUE THREAD

**Issue by phocean** [caido/caido#432]
In the intercept section, the ID column is not sorted as numbers, but as text, so it does not work as expected.

Also, as date sorting does not seem to work, so at this moment there is no way to change the history order based on the sequence or the date.

**Comment by Sytten** [comment]
Date is currently not sortable, that is a feature request I can open after this is done.
@Corb3nik I would expect this might be due to the recent changes in the frontend table since nothing changed backend wise on that front for a long time.
