### ISSUE TITLE
Sidebar number is cut in half

### ISSUE THREAD

**Issue by Sytten** [caido/caido#446]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

![image](https://github.com/caido/caido/assets/2366731/c4ddfbf7-57b0-4b9a-9a09-f149365c3fa0)

**Comment by Corb3nik** [comment]
Closing as this seems to be caused by an outdated browser
