### ISSUE TITLE
Download links are confusing in dashboard

### ISSUE THREAD

**Issue by Sytten** [caido/caido#453]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

We should split the sections for desktop and cli, improve readability and explain the difference between the two

**Comment by Corb3nik** [comment]
![Image](https://github.com/user-attachments/assets/df8a5f0e-16ff-4009-a1e9-9d7cbb6db49e)

Desktop vs CLI sections are pretty clear in the dashboard right now.

As for the explanation between the two, this should be handled outside of the dashboard
