### ISSUE TITLE
Large screen support

### ISSUE THREAD

**Issue by Sytten** [caido/caido#476]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

- [ ] Align top cards
<img width="1047" alt="Screen Shot 2023-06-13 at 11 49 46 AM" src="https://github.com/caido/caido/assets/2366731/b26a3a4d-8ebc-43fa-a7b9-47bd5ae255ea">
- [ ] Add max width to cards
<img width="1172" alt="Screen Shot 2023-06-13 at 11 47 57 AM" src="https://github.com/caido/caido/assets/2366731/ecee4fa5-7715-4ed2-be39-7a7d212c07c3">

**Comment by Corb3nik** [comment]
Closing this. This issue is too vague
