### ISSUE TITLE
Search not working in the projects page

### ISSUE THREAD

**Issue by Res260** [caido/caido#48]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- 
### Bug description

On the projects page, I can't seem to type on the search field.

### How to reproduce

1. Go on the projects page
2. Click the "search" textbox
3. Type stuff.

When typing one char at a time (same char), this seems to happen:
First char: nothing?
Second char: Some filtering is done, but the char does not appear in the textbox
Third char: the char appears once on the textbox

Weird behavior. Nothing on the webdev console.

### Environment & setup

OS: Windows 10
OS version: 21H1
Caido version: 0.7.9

**Comment by Corb3nik** [comment]
Hey 👋 Thanks for submitting this issue.

Just to be clear, when you say that typing the first char does "nothing", are you saying that the search textfield shows up empty when you type?

I'm testing this on Firefox/Chrome (macOS) and the search seems to work on my end.

One thing to note though: the project's search is performed against all the fields in the table. So when you search for "asdf", you're searching against the project's name, path, `created at` and `updated at` fields.

**Comment by Res260** [comment]
I should have recorded my screen while doing it haha.
When I type a char and it does "nothing", I mean it in the litteral sense: the char I typed does not appear on the textbox, and the results dont get filtered.

I'll try to reproduce in the next days (dont have my computer rn)

**Comment by Corb3nik** [comment]
This looks fixed, we've done a lot of changes to the projects page since :)
