### ISSUE TITLE
Add model gpt-3.5-16k in assistant

### ISSUE THREAD

**Issue by Sytten** [caido/caido#490]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

New model that should be easy to support, we just need a different credit multiplier.

**Comment by Corb3nik** [comment]
gpt-3.5-16k is deprecated now
