### ISSUE TITLE
Allow auto-resize columns to fit available space

### ISSUE THREAD

**Issue by Sytten** [caido/caido#492]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Initial look of the app is not super great on some devices because the columns dont take all the available space.
A user also asked for a way to "reset" to the columns to the screen size.

This is challenging since columns will overflow the screen due to the amount of information.

**Comment by Corb3nik** [comment]
This is fixed with the table rework https://github.com/caido/proxy-frontend/pull/1024
