### ISSUE TITLE
Custom keybindings/shortcuts support

### ISSUE THREAD

**Issue by andreystepanov** [caido/caido#494]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Add support for custom keybindings to exposed actions, such that user can redefine default configuration.

### Use cases

Some of the default keybindings simply not working on my current setup.

I'm on Linux (`NixOS`) and using Firefox browser for UI (`systemd` service running `backend` and custom Firefox profile for `frontend`).

And default keybindings conflicting with FIrefox's default shortcuts.

- `CTRL+R` refreshes the page, instead of sending request to `Replay`.
- `CTRL+F` enables native Firefox search, instead of Caido' `Editor: Search`. 
- `CTRL+I` enables native Firefox `Page Info` functionality, instead of Caido' `Navigation: Go To HTTP History`. 
- etc.

Seems like the only one that actually works is `CTRL+Enter` :)

So anyone who doesn't use Electron app faces the same issue.

For the reference, here's a list of default Firefox shortcuts:
https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly

**Comment by Sytten** [comment]
Thanks for the report @andreystepanov, it's a bit sad to hear that shortcuts are not working for you.
Usually the shortcuts are supposed to override the firefox defaults except some of them that we know we can't override so that is a bit weird, but definitely allowing overrides is necessary.
