### ISSUE TITLE
Explain types of attacks better in automate

### ISSUE THREAD

**Issue by Sytten** [caido/caido#498]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

We could start with simple tooltips, ideally we would have a more visual way of displaying the automate.

Idea I had a while ago:
![image](https://github.com/caido/caido/assets/2366731/232f8092-0d45-41e3-ae5c-17891d266fcb)

### Use cases

- Make it easier to use the automate

**Comment by Corb3nik** [comment]
Added tooltips next to each strategy via https://github.com/caido/proxy-frontend/pull/1419
