### ISSUE TITLE
Send to replay doesnt send the edits to a request

### ISSUE THREAD

**Issue by Sytten** [caido/caido#509]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

Right now I believe that the changes made in intercept are not used when doing a send to replay/automate. I think this is because we duplicate the request using the ID?

**Comment by Rhynorater** [comment]
Potentially related to #402
