### ISSUE TITLE
UX: It would be easier to read tables of data if there were alternating colors on each row

### ISSUE THREAD

**Issue by dee-see** [caido/caido#51]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

![ux](https://user-images.githubusercontent.com/7252342/141007802-cb09ae24-821e-401a-8ca0-de9163a29fae.png)

I find myself double checking if I'm really looking at the correct row. It's tough to visually make sure what I'm looking in the right column is really on the same row as what I'm looking in the left column. Maybe I'm just old. :older_man:  In any case I think a style with alternating row colors (kind of like this https://getbootstrap.com/docs/4.0/content/tables/#striped-rows) would help with readability.

We have the highlight on hover though so that's better than nothing

### Use cases

General Caido usage

**Comment by Corb3nik** [comment]
Closed via https://github.com/caido/proxy-frontend/pull/877

Added some borders between the cells and rows to make it clearer. Hopefully this helps 🙏 

<img width="1249" alt="Screenshot 2023-05-12 at 4 58 06 PM" src="https://github.com/caido/caido/assets/6225588/a56abda8-667c-4569-a7ce-0f2c7442ce00">
