### ISSUE TITLE
Change default selection and ordering of the Filter Like/Not Like/Contains/Not Contains options

### ISSUE THREAD

**Issue by hpy** [caido/caido#512]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

The current implementation of Filters when using `[Request] Raw` and `[Response] Raw` defaults to using the `Like` Custom filter. 

The primary usecase for `Search` is to find all requests/responses that match a given string. I.E, a `Contains` search filter. However, because the default option is a `Like` filter you either have to add wildcard selections around your search `%searchphrase%` OR update the Filter type to `Contains`. This slows down workflows considerably, and I find myself frequently accidently performing `Like` searches by accident. 

This also sporadically freezes Caido and its Chrome windows (I cannot get this to happen every time, its sporadic, but it ONLY happens when I do a LIKE search without wildcards), forcing me to hard reboot the Caido instance.

I suggest reordering the Custom filters to have Like/Not like at the end.

### Environment & setup

OS: Ubuntu
OS version: 22.04.2 LTS
Caido version: 0.26.0

**Comment by Sytten** [comment]
The filters are due for an overhaul, but I agree this would be a good improvement with low effort.
The freeze on like is interesting, I saw this issue in the past but didnt have time to investigate.

**Comment by Corb3nik** [comment]
Thanks for the issue!
