### ISSUE TITLE
100% usage on CA page

### ISSUE THREAD

**Issue by Sytten** [caido/caido#516]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

Report by user:
> High CPU usage and eventual lockup on CA cert install page: 
When viewing the "CA Certificate Installation" page in Caido, all 8 of my cores go to 100% usage, apparently due to WebKitWebProcess processes. If I leave the CA Cert page open for a few minutes, Caido eventally locks up and I have to force quit.

### Environment & setup

OS: Kali Linux on VMWare (Windows Host)
Caido version: 0.26.0, Desktop

**Comment by Corb3nik** [comment]
Seems to be a webkitgtk specific bug. The CA Certificate page triggers multiple repaints for no(?) reason

<img width="1440" alt="Screenshot 2023-07-02 at 11 18 26 AM" src="https://github.com/caido/caido/assets/6225588/65c6bf6a-53a3-46e6-8445-cfefb82599de">
