### ISSUE TITLE
Student discount

### ISSUE THREAD

**Issue by Sytten** [caido/caido#531]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Add the information to the marketing website:

>We’re offering 50% discount for students for the annual plan.
>
>If you are a student and want to receive the discount, please send an email to info@caido.io with subject “Student Discount” and attach a proof of enrolment. 
>
>We will verify your education status and send you the discount code via email.

**Comment by Corb3nik** [comment]
This was published on september 27th 2023
