### ISSUE TITLE
Add sort with the response length in the http history tab

### ISSUE THREAD

**Issue by hashem-mo** [caido/caido#532]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description
add the ability to sort the http history with the length descending/ascending 

### Use cases
I need it a lot while trying to avoid duplicated responses

**Comment by agnosticlines** [comment]
This is really useful when testing auth bypasses on routes, you can filter by the size to see sites that have extra information in the request
