### ISSUE TITLE
`Send to Replay` should support replay collections other than the `Default Collection`

### ISSUE THREAD

**Issue by hpy** [caido/caido#539]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Currently, when selecting `Send to Replay` all requests are automatically appended to the `Default Collection` (or whatever it has been renamed to by the user). Instead, when a request is selected to `Send to Replay` via the right click menu, it should act similar to the `Add in Scope` menu option by allowing the user to select which Replay Collection you want the request to be sent to. The top option would be `Default Collection`.

Additionally when inside the Replay window, if a request is selected to `Send to Replay` (i.e you may want to make a variant of the request) it should by default be added to the existing collection and NOT added to the Default Collection (as currently is the case).

The keyboard shortcut would default to still send all requests to the `Default Collection`. Optional: It could also be a new user option to set a custom default collection.

**Comment by Corb3nik** [comment]
I've wanted this feature for a while, but was struggling to figure out the best approach for this.

Loving the suggestions here, I'll definitely look into implementing those 👍

**Comment by shriyanss** [comment]
> I've wanted this feature for a while, but was struggling to figure out the best approach for this.
> 
> Loving the suggestions here, I'll definitely look into implementing those 👍

Hi @Corb3nik 

You can add an option to `Make default` after the three dots are clicked on a particular collection. Later, when the user triggers the action `send to replay`, a variable can be accessed to know which collection is the default one

<img width="393" alt="image" src="https://github.com/caido/caido/assets/71912662/41bf4b77-a67c-4375-89d8-5c7a7a512a04">


Regards
@shriyanss

**Comment by Rhynorater** [comment]
Yes, I totally agree with @shriyanss. I think that is the best way to implement this.
