### ISSUE TITLE
Caido crashes when there is no match in the search tab

### ISSUE THREAD

**Issue by hashem-mo** [caido/caido#540]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description
In the search tab when you search for anything that does not have any matches, Caido will freeze and you will have to restart it

### How to reproduce
1. Go to the search tab and search for any random thing that  does not exist the program will freeze

### Environment & setup

OS: Windows
OS version:  10
Caido client:  Caido Desktop
Caido version:  0.27.2

**Comment by Sytten** [comment]
Did you experience this freeze on a particular project? If so, how large is it?
We will try to reproduce it on our own, but we might need to discuss it further on discord in private if you have time.
If you can record a small video with loom or something similar that would be super helpful.

**Comment by hashem-mo** [comment]
I experienced it specifically on 2 projects 12GB and 4GB.
I don't know why but it doesn't always happens, i can not reproduce it at moment but, i'm sure of it as bug because it happened with me many times.
Yes, i have time that would be good

**Comment by Corb3nik** [comment]
I think I managed to reproduce it:
1. Start with a table containing multiple rows
2. Scroll to the middle of the table
3. Apply a filter/scope that will result in an empty table

The app will freeze (might be caused by an infinit loop in the JS)
