### ISSUE TITLE
Toggle GET/POST strips data after colon (:)

### ISSUE THREAD

**Issue by nonsleepr** [caido/caido#543]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

When the request contains colon (`':`), the data after the colon would be lost after selecting "Toggle GET/POST".

### How to reproduce

For example, the following request:
```http
GET /test?parameter=x:tail HTTP/1.1
Host: localhost

```
After toggling to `POST` would look like this:
```http
POST /test HTTP/1.1
Host: localhost

parameter=x
```

Similarly, conversion to `GET` looses data:
```http
POST http://localhost/test HTTP/1.1
Host: localhost

parameter=tail
```

becomes completely broken:
```http
GET http?parameter=x:tail HTTP/1.1
Host: localhost

```

### Environment & setup

OS: Windows
OS version: 11
Caido client: Caido Desktop
Caido version: 0.27.2

**Comment by nonsleepr** [comment]
Please also take a look at `Content-Type: multipart/form-data`, when converted to GET it becomes completely broken.

**Comment by Corb3nik** [comment]
That issue is tracked via https://github.com/caido/caido/issues/419. Fixing that is a bit more involved :)
