### ISSUE TITLE
Add the ability to make a new request in the reply

### ISSUE THREAD

**Issue by hashem-mo** [caido/caido#546]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description
Add the ability to make a new blank tab in the reply and build it from the 0 

### Use cases
sometimes i need to customize a request and that i do not have a similar one in the HTTP histroy

**Comment by CrunchV1** [comment]
Hey @hashem-mo, do you mean this? :)
![image](https://github.com/caido/caido/assets/91413622/831fe0c4-d8e2-4841-b64c-a022ec277a7a)

**Comment by hashem-mo** [comment]
Yes, exactly. 
Is it unreleased yet, i'm on the latest version

**Comment by Sytten** [comment]
It's been there for a long time, can you verify? Might be a UI bug we need to fix

**Comment by hashem-mo** [comment]
I use caido everyday 
Here is how it looks like
![Web capture_7-8-2023_181545_127 0 0 1](https://github.com/caido/caido/assets/107648396/e9143163-b6cd-40ea-95b0-d6766e4785fe)
I'm using the free version

**Comment by hashem-mo** [comment]
I just found out it exists, just wasn't shown i needed to pull it.
Please make it shown by default that was so hard to fighure out

**Comment by Sytten** [comment]
Ha yeah I see you reduce the sidebar very small, I will open an issue for that
