### ISSUE TITLE
Make discoverability of request/response search more obvious

### ISSUE THREAD

**Issue by Sytten** [caido/caido#557]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

A user reported:

> [...] it would be a lot better if you added a search bar at the bottom of the replay tab to search through the req/response. 

We have this feature, just not super discoverable (ctrl + f when clicked in the panel)

**Comment by Corb3nik** [comment]
It's unclear whether this is a discoverability issue or an issue related to
- https://github.com/caido/caido/issues/517
- https://github.com/caido/caido/issues/497

**Comment by Corb3nik** [comment]
Closing this for now, haven't heard much about this issue
