### ISSUE TITLE
Allow user to delete their account in the dashboard

### ISSUE THREAD

**Issue by Sytten** [caido/caido#563]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Right now users have to send us an email, it would be better if they could delete everything themselves.

### Use cases

- Easier GDPR compliance for us

**Comment by Corb3nik** [comment]
This has been added on March 20th 2024
