### ISSUE TITLE
Wireshark-like filters

### ISSUE THREAD

**Issue by Corb3nik** [caido/caido#566]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

In order to offer a more powerful filtering experience, it would be nice to have a wireshark-like filter system, where users can specify strings like

```
!(request.host == "b.domain.com" && request.path == "/leetpath")
```

instead of using the UI to build filters.

Note: Some users enjoy the current filter UI, so we'll need a system that allows both the wireshark-like filters, as well as a UI builder

**Comment by rew1nter** [comment]
> we'll need a system that allows both the wireshark-like filters, as well as a UI builder

When you implement this, I would suggest that you only allow one type of filtering to be activated at a time to avoid complexity.

**Comment by Corb3nik** [comment]
Closed via https://github.com/caido/proxy-frontend/pull/1129
