### ISSUE TITLE
UX: When clicking on New Request in the Replay screen the focus should be moved to the new request

### ISSUE THREAD

**Issue by dee-see** [caido/caido#57]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

If I click on New Request I'm very likely to want to write something in that request tab next. It would save a click :)

### Use cases

General usage

**Comment by Corb3nik** [comment]
Seems to be fixed.

https://user-images.githubusercontent.com/6225588/154164803-6a10a1ea-aac0-4a59-97a2-07ea92304d27.mov
