### ISSUE TITLE
Extension filter should always be %.ext

### ISSUE THREAD

**Issue by Sytten** [caido/caido#576]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Most of the time if a user wants to exclude `.js`, they don't care if it has something before (`.10.js`). If they use the `!=` filter, it won't filter it. They would have to use a `LIKE` with `%.js`. We should probably always do that.

The reason it wasn't done that way is simple, you can't index a `%something` so queries are slow if you only use that filter. I might have to get creative and store the path in reverse order (`sj.%` can use an index)

### Use cases

- Better UX

**Comment by Corb3nik** [comment]
This should be a non-issue now that users use HTTPQL: `req.ext.cont:"js"`
