### ISSUE TITLE
JSON Pretty view in other tabs (replay, etc.)

### ISSUE THREAD

**Issue by shriyanss** [caido/caido#587]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Hi there,
A feature to prettify the JSON body would be great.

(Please add different colors for param names and values)

### Use cases

- Increased readability
- Easy to play around with parameters

**Comment by Corb3nik** [comment]
Closing this in favor of https://github.com/caido/caido/issues/294
