### ISSUE TITLE
Request modification buffer appears to be global

### ISSUE THREAD

**Issue by dee-see** [caido/caido#60]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

Video will explain it better than words

https://user-images.githubusercontent.com/7252342/141313283-5fa71567-4f4e-4808-9d13-20a935cc48b2.mp4

### How to reproduce

Edit multiple requests but don't send them

### Environment & setup

OS: Arch Linux
OS version: Kernel 5.14.16
Caido version: 0.7.10

**Comment by Sytten** [comment]
We should also add an indicator to tell the person if the request was modified or it is the original history entry. And a way to reset to the original request.

**Comment by Corb3nik** [comment]
> We should also add an indicator to tell the person if the request was modified or it is the original history entry.

What problem is this trying to solve? The original request in the replay history will always be the 1st request.

**Comment by Sytten** [comment]
Thats not what I meant. Like by default when you send a new request it displays the last sent data. If you modify it and decide thats not what you wanted to do, you have go to history left (<) then right (>) again. And there is not indicator to say that you modified it. I was thinking more like a vscode style icon when the file is not saved. Just an idea.

**Comment by Corb3nik** [comment]
Converting this issue into a bug report :)

Regarding the feature request to allow users to edit multiple requests at once, I've created a seperate issue: #66

**Comment by dee-see** [comment]
I struggle to understand the difference between fixing this and implementing support for editing multiple requests.

Should I understand that the immediate fix here will be to "lock" the user in a request until it's sent?

**Comment by Corb3nik** [comment]
Yeah, we added a new library to fix some of the other bugs you highlighted, which inherently fixes this bug, but doesn't allow editing multiple requests at once :(

So at the moment, if you:
1. Edit a request but not send it
2. Select a different tab/request
3. Edit the newly selected request

...the changes from your first request won't end up in your second request. Your changes on the first request will be lost though.

Do you edit multiple requests often? I personally don't, but if you do I can make #66 more of a priority :)

**Comment by dee-see** [comment]
> Do you edit multiple requests often? 

I... don't think I do? 😂 I guess I'll figure out the answer to that soon haha
