### ISSUE TITLE
[Feature] "Sticky"  Automated Edit on requests in HTTP History

### ISSUE THREAD

**Issue by douglasfsmn** [caido/caido#600]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Add a configuration option to a project to have "Sticky" Automated Edit, which would always show the Automated Edit request  instead of Original request. 

### Use cases

Useful when modifications are made through Match & Replace (like adding identifying headers for Bug Bounty), it is necessary to always select Automated Edit before using right-click features from the Request pane (Send to Replay, Send to Automate,  Copy as cURL, etc.).  Having an option on each project to make showing Automated Edit "sticky" would save clicks and save mistakes.

**Comment by Sytten** [comment]
Hi @douglasfsmn thanks for the report, I will close in favour of https://github.com/caido/caido/issues/496 let me know if that is not the same issue :)

**Comment by douglasfsmn** [comment]
Hello - Yes - this is the same issue. I see that you have already closed [#600](https://github.com/caido/caido/issues/600). I did go through first to try to find duplicate - clearly I missed that one.

Thanks for your support!
Doug

------- Original Message -------
