### ISSUE TITLE
Linux Desktop (AppImage) don't open the login page

### ISSUE THREAD

**Issue by i5nipe** [caido/caido#608]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

I'm trying to use Caido desktop (AppImage) on an Ubuntu 22 LTS, but it just don't work, when I click the login button it don't open any page on browser and the Caido App just loads forever waiting for the authentication, I have tried to install another browsers, It don't open any page anyways. But if I go to localhost:8080 I can log in normally.

### Environment & setup

OS: Ubuntu 22.04.3 LTS
Caido client: Caido Desktop
Caido version: 0.28.0, 0.29

**Comment by Sytten** [comment]
Thanks for reporting, we will investigate. We do have a lot of trouble with the desktop version on linux...

**Comment by chapsec** [comment]
Same issue here :

Linux: Ubuntu 22.04.3 LTS (Mate) 
Caido : caido-desktop-linux-v0.29.0-a8cef39b.AppImage

With the URL localhost:8080 i can bypass the issue.  Thank to [i5nipe](https://github.com/i5nipe)

**Comment by Sytten** [comment]
This was fixed on 0.29.1
