### ISSUE TITLE
UI shifts to left after clicking the project change button

### ISSUE THREAD

**Issue by rew1nter** [caido/caido#610]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description
Clicking the project change button, in history tab, shifts the UI to left. Then you have to reload to fix the the UI

![image](https://github.com/caido/caido/assets/64508791/ef15dfd5-c734-4cd4-8d0c-626f3b751528)

### How to reproduce
1. Open caido with a project
3. Switch to history tab
2. Click the project button 

### Environment & setup

OS: Arch
Caido client: Chrome, Brave (firefox not tested)
Caido version: 0.29.0

**Comment by Corb3nik** [comment]
@rew1nter Do you have steps to reproduce this reliably? 

I've seen this bug a few times, but havent been able to reproduce this reliably yet.
