### ISSUE TITLE
Recently added columns are missing the sort feature

### ISSUE THREAD

**Issue by rew1nter** [caido/caido#619]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description
These columns cannot be clicked for sorting by:
Query, Extension, Source, RT and Sent At

### How to reproduce

Try clicking any of the aforementioned columns 

### Environment & setup

Caido: 0.29.0

**Comment by Sytten** [comment]
New columns are not orderable because it requires a lot more work than just adding new data and even filtering. But yeah good thing to point out.
