### ISSUE TITLE
When searching in a request/response there should be a way to move from match to match

### ISSUE THREAD

**Issue by dee-see** [caido/caido#62]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

With a hotkey and/or buttons in the UI it should be possible to navigate between the locations that matched my search in a request/response so I can quickly review all the matches to see if it's what I'm looking for.

Somewhat related to https://github.com/caido/caido/issues/54

### Use cases

Searching for something specific in a large response with multiple matches

**Comment by Corb3nik** [comment]
Fixed by integrating the Monaco editor
