### ISSUE TITLE
Search Tab Re-work

### ISSUE THREAD

**Issue by Rhynorater** [caido/caido#634]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

The search tab in Caido needs some work. We need a search bar. Ideally a search bar with a query language, but at minimum we need a bar where we can put in a string and see every request and response that contains that string. 

We also need regexes supported here.

Ideally, we could also click on a search result to see a preview of that request/response, and then have a button that would take us to that search result in the HTTP History tab. This is a big pain point in Burp and something y'all could do to stand out. 

Having auto-updating search results would also be cool.

Specifying where to search would also be cool (req headers, req body, etc.

It would also be great if you could jump to the matching string in the response body or highlight it somehow.

**Comment by Nishantbhagat57** [comment]
+1

**Comment by Corb3nik** [comment]
Closed via https://github.com/caido/proxy-frontend/pull/1129
