### ISSUE TITLE
Add New Convert Workflow Features

### ISSUE THREAD

**Issue by Rhynorater** [caido/caido#635]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description
I would love to see these features in convert workflows:
* JSON minify 
* JSON Pretty-ify
* Display & Prompt (This would take the current result, pop up a box allowing the user to edit, then output the result to the next box)
* Trim whitespace
* Match & Replace
* Match & Replace with regex

I know that all of these (maybe with the exception of Display & Prompt are available via the `JavaScript` or `shell`  workflow items, but I think these should be added in natively, especially the JSON ones.

**Comment by Nishantbhagat57** [comment]
+1

**Comment by rew1nter** [comment]
I only vote for Display & Prompt and Match & Replace. Something like integrating JSON minification/prettification is an overkill when shell node workflow is already here. 
You can just type `jq` and prettification job done. This even comes as the default shell node example. I don't think its a good idea to push devs to integrate something that takes 1 to 5 minutes to setup yourself. After all it these are the reason why shell node exists.

**Comment by Sytten** [comment]
We wont add the display/prompt for now since its not really in line with the spirit of convert workflows but I am adding all the other nodes
