### ISSUE TITLE
Make Convert output popups an option for Replay as well

### ISSUE THREAD

**Issue by rew1nter** [caido/caido#646]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description
Currently, History shows you a pop-up of the converted output instead of overwriting the existing data. In replay however, it always overwrites the data. It's often useful to only view the data like History when you don't want to overwrite the actual request.   

### Use cases
View request conversion result without modifying the request

**Comment by Rhynorater** [comment]
@rew1nter Dont forget to upvote your own issue.
