### ISSUE TITLE
Automate Mark Placement is Bugged

### ISSUE THREAD

**Issue by Rhynorater** [caido/caido#648]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

When you have a request in automate:
1. Mark a location
2. Launch the attack
3. Go back, modify a location directly before the mark, but not including the mark
4. Press attack again, and note the mark is in the wrong place

### Environment & setup

OS: Windows
OS version: 11
Caido client: Desktop
Caido version: 0.29.0

**Comment by Corb3nik** [comment]
Tracking this via #758
