### ISSUE TITLE
Select project can be very slow when downloading a new version of Caido

### ISSUE THREAD

**Issue by Sytten** [caido/caido#65]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

When selecting a project build using an earlier version of Caido, it can take a long time to respond.
This is due to database migrations being applied and there is not much to do except add a nicer interface for it.
It is also unclear what happens if a user reloads the page at this point and tries to select another project.

### How to reproduce

1. Build a project using an old caido version
2. Launch a newer version
3. Try to select a project

### Environment & setup

Caido version: 0.7.10

**Comment by Corb3nik** [comment]
Closed via https://github.com/caido/proxy-frontend/pull/396
