### ISSUE TITLE
Pressing TAB moves the focus to other elements on the page instead of writing spaces

### ISSUE THREAD

**Issue by rew1nter** [caido/caido#658]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description
Typing `Tab` in the editor doesn't add spaces. Instead, it just keeps cycling through clickable elements on the UI.

Not sure if `Tab` in this release was supposed to cycle back n forth between the editors. If that is the case, It's still a bug cause the focus keeps moving on to other elements of the UI 

### How to reproduce
1. Go to replay
2. Click an editor
3. Press tab x 5

### Environment & setup

OS: Arch
OS version: 6.6.1-arch1-1
Caido client: Chromium
Caido version: 0.29.2

**Comment by Corb3nik** [comment]
In order to allow people to tab out of the editor anyway, we could use VSCode's approach to toggling tab trapping: https://code.visualstudio.com/docs/editor/accessibility#_tab-trapping
