### ISSUE TITLE
Revisiting shell node workflow shows incorrect timeout number on the UI

### ISSUE THREAD

**Issue by rew1nter** [caido/caido#659]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description
This is a UI bug. The feature works as expected

### How to reproduce
1. Create a shell node workflow 
2. Save with 36000 timeout
3. Refresh the webpage
4. Revisit the workflow 
5. See that the timeout is now showing 1000

### Environment & setup

OS: 
OS version: 
Caido client: 
Caido version:

**Comment by Corb3nik** [comment]
Closed via https://github.com/caido/proxy-frontend/pull/1127
