### ISSUE TITLE
Add `Has Response` field to caido Export schema

### ISSUE THREAD

**Issue by rew1nter** [caido/caido#660]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description
Currently, the response field needs to be checked manually for data. This simple boolean field would save parsing time and code.

### Use cases
Save programming and parsing time

**Comment by Sytten** [comment]
Trying to understand the usecase here.
1. json or csv
2. Since you have to parse the whole json anyway, why is it faster to check for Boolean vs an empty object?

**Comment by rew1nter** [comment]
1. JSON
2. You're right. Back then I for some reason didn't realize that : )
![image](https://github.com/caido/caido/assets/64508791/b0b1115b-c104-4dfc-80d7-36c38b782711)
