### ISSUE TITLE
Base64 decode node should work regardless of padding

### ISSUE THREAD

**Issue by Sytten** [caido/caido#674]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Right now you have to specify padding in advance, it should try both since it usually what the user expects.

### Use cases

- Avoid having two workflows

**Comment by Corb3nik** [comment]
Closed via https://github.com/caido/proxy-backend/pull/918
