### ISSUE TITLE
Ability to change syntax highlighting for better contrast

### ISSUE THREAD

**Issue by Riddle1001** [caido/caido#681]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description
**It's a little harder for me to read Caido due to lower contrast on text. Would love option for different syntax highlighting options** 
#### Caido:
![image](https://github.com/caido/caido/assets/75004732/1567d47b-daa9-49ec-888e-0a86baa39490)
#### Another proxy:
![image](https://github.com/caido/caido/assets/75004732/534a5583-1001-47db-a1f9-9964925cddd4)

**Comment by Riddle1001** [comment]
Found an extension that helps https://chromewebstore.google.com/detail/font-changer/obgkjikcnonokgaiablbenkgjcdbknna

New: 
![image](https://github.com/caido/caido/assets/75004732/d8f67e50-4a81-488b-ade5-08c2c21bb40e)


Old: 
![image](https://github.com/caido/caido/assets/75004732/e0245dca-29be-4132-8962-934bf0ee6aa0)

**Comment by Corb3nik** [comment]
Contrast seems to be better now
![Image](https://github.com/user-attachments/assets/d93fc58e-1bda-482e-a609-014e8a397b61)

If you think this is still an issue, let me know and I'll open it up :)
