### ISSUE TITLE
Auto Scroll Issue in Replay When Sending Long Requests

### ISSUE THREAD

**Issue by Riddle1001** [caido/caido#683]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description
When you replay a request that has a scrollbar, the __raw http request text entry__ field automatically scrolls up

### How to reproduce
1. Have a long request
2. Send it to replay
3. Scroll all the way down in in the raw request field
4. Send it
5. See you automatically get scrolled up after sending

### Environment & setup

OS: Debian
OS version: 6.2.0-37-generic
Caido client: Chrome
Caido version: caido_0.29.2_cli

**Comment by Corb3nik** [comment]
This should be fixed as of v0.37.0

https://github.com/caido/caido/assets/6225588/ff1ff19d-2868-4825-8fd0-5ecec1d26ee7

@Riddle1001 Let me know if I misunderstood and I'll reopen the issue :)
