### ISSUE TITLE
Setting high number of null payloads in automate leads to crash

### ISSUE THREAD

**Issue by Riddle1001** [caido/caido#686]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description
Setting `Number of payloads to generate` to a high number causes Caido to crash.

*I wanted to perform an "infinite" heartbeat on an endpoint*

### How to reproduce
1. Send an endpoint into Automate
2. Put a high number of payloads to generate e.g `99999999`
![image](https://github.com/caido/caido/assets/75004732/0242e5a1-ca63-440b-9ec5-462aba55507d)
![image](https://github.com/caido/caido/assets/75004732/5716ead5-6b88-4a76-b17c-b446aeb03789)

### Environment & setup

OS: Debian
OS version: 6.2.0-37-generic
Caido client: Chrome
Caido version: caido_0.29.2_cli

**Comment by Sytten** [comment]
Good catch I dont think I ever tried that before. That is for sure putting pressure on the system.

**Comment by Sytten** [comment]
This is likely due to the fact that we currently pre-generate the payloads and it OOM, we need essentially to do on-demand payload generation.

**Comment by Sytten** [comment]
Working on it with the automate rework, should be landed in the next release
