### ISSUE TITLE
Match & replace breaks the JSON

### ISSUE THREAD

**Issue by shriyanss** [caido/caido#690]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

The match and replace rules doesn't properly replaces the character (in JSON)

### How to reproduce

I was testing response manipulation attacks for response body (JSON). I added some rules like `"maxLimit":5` -> `"maxLimit":10` or `"performAction":false` -> `"performAction":2` to increase the limits, but it broke the JSON. E.g.:-
Response (original):-
```json
{
    "data": {
        "...Limit...": {
            "can...": true,
            "can...": false,
            "can...": false,
            "...Count": 2,
            "...Count": 0,
            "...Count": 2,
            "...Count": 11,
            "...Count": 1,
            "maximum...": null,
            "maximum...": 10,
            "maximum...": 1,
            "__typename": "...Limit..."
        }
    }
}
```
Response (automated edit):-
```json
{
    "data": {
        "...Limit...": {
            "can...": true,
            “can... ":true,"   <- Modified
            can...”: true,  <- Modified
            "...Count": 2,
            "...Count": 0,
            "...Count": 2,
            "...Count": 11,
            "...Count": 1,
            "maximum...": null,
            "maximum...": 15,  <- Modified
            "maximum...”:5," <- Modified
            __typename ":"
            ...Limit... "}}}
```

Notice that the `"` is replaced with `”` in some cases, which is causing parsing errors. Also, it has added a new line after `"` (notice the second modified param)

While I created these rules, I simply copied & pasted the parameter as `"doSomething":false` from the HTTP history to both match and replace, and in replace section, just made the `false` to `true`

### Environment & setup

OS: Mac OS
OS version: 14.1.1
Caido client: Caido Desktop
Caido version: 0.29.2

**Comment by Sytten** [comment]
This is a mac os specific thing due to spellcheck, we need to pass `spellcheck="false"` to our inputs to avoid that. It is very annoying.
