### ISSUE TITLE
Slack like system for node inputs

### ISSUE THREAD

**Issue by Sytten** [caido/caido#694]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Currently all inputs are stacked in one column. It would be nice to offer a system similar to slack notifications where you can specify rows and columns for nicer visual experience.

### Use cases

- Improve node UX

**Comment by Corb3nik** [comment]
This seems to be related to the old workflow system
