### ISSUE TITLE
Allow for scoping on Workflows/Filter, general or project specific

### ISSUE THREAD

**Issue by Riddle1001** [caido/caido#696]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Allow for the customization of workflows and filters with specific scoping options. This would enables users to save a workflow or filter either for a single project or on a globally. Perhaps also for Match & Replace

**Comment by Sytten** [comment]
We are aware of the current limitations. Having both project specific and global for each type of object is not an easy problem to solve since we need to factor in a lot of consideration (backups, sorting, filtering, activation list, etc). It will be an ongoing process.

**Comment by ly4e** [comment]
similar to the " Make the workflows shareable between projects #582 " item. though would love to be able to chose which items are shared globally and those that are only available locally to a specific project (match/replace, filter, workflows, etc)

**Comment by Sytten** [comment]
I am going to close this issue since it's not specific enough for us.
- Workflows are now global
- https://github.com/caido/caido/issues/995 tracks the Match&Replace Global
- https://github.com/caido/caido/issues/1001 tracks the Filter Global
