### ISSUE TITLE
Add customizeable hotkeys for convert workflows

### ISSUE THREAD

**Issue by Riddle1001** [caido/caido#700]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

I would like to assign a custom hotkey, i.e ctrl + u for a convert workflow like URL encoding, will be much faster than clicking twice (plus the time to find it within the menu and submenu)

**Comment by Sytten** [comment]
Duplicate of https://github.com/caido/caido/issues/606
