### ISSUE TITLE
Make the HTTP request/response display font configurable for improved readability

### ISSUE THREAD

**Issue by its-red-beard** [caido/caido#701]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Caido uses fixed fonts for displaying HTTP request/response, such as Courier New in Windows, limiting user customization and potentially hindering accessibility. This feature request proposes the implementation of configurable fonts for it, including the font size. AFAIK the current implementation changes the entire UI font size.

### Use cases

Individuals with specific font preferences or readability needs can tailor Caido to their liking. Personally for me it's harder to read with the Courier New font in Windows:

![image](https://github.com/caido/caido/assets/154296481/8453d60f-e993-4405-b30d-bd534b5dab7c)

compared to the Cascadia font:

![image](https://github.com/caido/caido/assets/154296481/f5051fdd-ab09-4ec5-969a-2a839e785ca2)

and better readability with bigger font size (without affecting the whole UI):

![image](https://github.com/caido/caido/assets/154296481/100e5265-9a6a-4ade-aa3a-317bf38a5738)

**Comment by Corb3nik** [comment]
@its-red-beard Courrier new is indeed a terrible font for the editor :(

I've changed the font to Consolas for next release. While it doesn't address the font-size configuration issue, hopefully it'll help with readability a bit.

![image](https://github.com/caido/caido/assets/6225588/d68b2398-8964-4419-9584-4aef11c6ae86)

**Comment by Corb3nik** [comment]
Added font-size configuration for next release. If the current font + font-size configuration isn't enough, let me know!

**Comment by b33fstrogan0ff** [comment]
Sorry for bringing this up again, but are there any plans to make it so users can change the request/response font? Would love to be able to set whatever mono/fixed-width font I want.

**Comment by Corb3nik** [comment]
@b33fstrogan0ff Wasn't planned, but I've created a new issue for this. Feel free to upvote it!

https://github.com/caido/caido/issues/1182
