### ISSUE TITLE
Release pages should indicate recommended and experimental for CLI and Desktop editions

### ISSUE THREAD

**Issue by zesty** [caido/caido#712]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

https://github.com/caido/caido/releases

Release pages should indicate recommended and experimental for CLI and Desktop editions.  The heading for the list of CLI downloads should be "CLI (recommended)" and the heading for the list of Desktop downloads should be "Desktop (experimental)". Alternately "... (recommended for linux)" for each to single out linux as per the FAQ. It's not entirely clear from the FAQ (see below) if Desktop is considered experimental for *all* platforms or only for linux.

### Use cases

Reduce FAQs for issues from grabbing the wrong edition.
https://docs.caido.io/faq.html
"WARNING: At the moment, Caido Desktop is considered experimental and does not perform as well as the browser on Linux."

**Comment by Sytten** [comment]
Agreed, we will rework the download page soon. We will also rewrite the desktop app, the current one has too many problems related the native OS webviews.

If others find this issue, we consider the desktop on all platforms experimental. But it works well on recent windows 10+ and macos 11+.

**Comment by Sytten** [comment]
@Corb3nik we should edit the text used in the release script to mention experimental on desktop before next release

**Comment by Corb3nik** [comment]
Added experimental label on linux desktop builds.

**Comment by Sytten** [comment]
Still think we should rework the marketing site download to make better
