### ISSUE TITLE
Add a page to inject custom CSS and JS in Caido UI

### ISSUE THREAD

**Issue by sw33tLie** [caido/caido#718]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Add a page to the settings featuring a text form that allows the execution of custom CSS and JS on the Caido UI.

### Use cases

This would make it easier - especially on the desktop version - for people to improve Caido's UI and add functionalities via JS that could then be shared with the community.
The devs could also see the most liked snippets and consider implementing them directly in Caido.

**Comment by Corb3nik** [comment]
Custom CSS done via https://github.com/caido/caido/issues/728

**Comment by PatrikFehrenbach** [comment]
🔫🐴
