### ISSUE TITLE
Remove animation on the sitemap arrow click

### ISSUE THREAD

**Issue by sw33tLie** [caido/caido#72]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

When clicking on the `q-tree__arrow` in the Overview page to see crawled paths of a domain, there's a little animation that delays the results a bit.
I propose to get rid of that animation entirely.

**Comment by Sytten** [comment]
I split the shift click in another issue https://github.com/caido/caido/issues/74

**Comment by Sytten** [comment]
This might be hard to do since it does some fetching in the background, including a recursive SQL query which can be slow depending on the size of the element to expand.
