### ISSUE TITLE
Sort by size please, it is needed for parameter discovery

### ISSUE THREAD

**Issue by prathvi2002** [caido/caido#725]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

**Comment by prathvi2002** [comment]
I can't sort by size nowhere. I am using Kali Linux. Tried both caido-cli and caido but can't sort by size sir.

**Comment by Sytten** [comment]
I am going to in favour of https://github.com/caido/caido/issues/729
There are some places you can't and some you can.
