### ISSUE TITLE
Cyberchef integration

### ISSUE THREAD

**Issue by sw33tLie** [caido/caido#73]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

It would be nice to have [Cyber Chef](https://gchq.github.io/CyberChef/) built within Caido.
It's open-source and it appears to be using Apache2 as license, so allowing:
- Commercial use
- Modification
- Distribution
- Patent use
- Private use

Everything is being done using javascript on the client, so it should be pretty easy to integrate and tweak.
Thoughts?

**Comment by Corb3nik** [comment]
If its not an issue, I think it would save a lot of time if we can re-use the javascript calls for the various encoding/encryptions/presets in Cyberchef...

We're definitely going to rewrite the UI though, there's a few thing I'd like to change. Here's a *very* rough draft of the direction I'm going in so far.

<img width="1077" alt="Screen Shot 2021-12-01 at 8 56 29 AM" src="https://user-images.githubusercontent.com/6225588/144247573-dba3ea4c-4082-4147-aefa-e947a8bcb2a1.png">
