### ISSUE TITLE
Add a Remove All Button to the Payloads List in Automate

### ISSUE THREAD

**Issue by evanconnelly** [caido/caido#732]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Presently, you can only remove one payload at a time from the payloads list. This can be problematic if working with a large number of payloads, for example, if the wrong payloads are inadvertently loaded. A new action, maybe a "remove all" button below the "remove button," would be helpful to clear the whole list.

i.e.
![mockup](https://github.com/caido/caido/assets/60989997/0198a204-0685-4830-9ddd-396c8b2b39ce)

### Use cases

To clear a large list of payloads without having to delete the entire automate session and make a new one.

**Comment by Corb3nik** [comment]
@evanconnelly We've updated the simple list to be an editor, so you should be able to select-all and clear the entire thing easily now.

Let me know if you think a button is still necessary.
![Image](https://github.com/caido/caido/assets/6225588/e7068985-7b3a-43f4-aad7-2d4d10621d94)

**Comment by evanconnelly** [comment]
@Corb3nik this looks great!
