### ISSUE TITLE
Add SNI overrides

### ISSUE THREAD

**Issue by sw33tLie** [caido/caido#741]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Add SNI overrides to Replay and Match&Replace:

![image](https://github.com/caido/caido/assets/47645560/2b060a7b-851b-4bc9-8326-dbb5936479c2)

- https://www.cloudflare.com/en-gb/learning/ssl/what-is-sni/

### Use cases

This can be used to sometimes bypass access controls in place

**Comment by Sytten** [comment]
@sw33tLie I shipped it for replay and automate, match&replace will have to wait.

**Comment by sw33tLie** [comment]
Thank you so much!
