### ISSUE TITLE
Closing desktop app causes a white screen 

### ISSUE THREAD

**Issue by Sytten** [caido/caido#745]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

User reported:
> sometimes (dunno exactly when) but when i close caido using the red X on the top right corner 
it becomes like this and then it takes time for it until it closes(sometimes i even end task from task manager)

![image](https://github.com/caido/caido/assets/2366731/0951227f-8182-46ff-963f-a3270673034b)

### Environment & setup

OS: Windows
OS version: ?
Caido client: Caido Desktop
Caido version: 0.30.4

**Comment by Corb3nik** [comment]
Closed via https://github.com/caido/proxy-desktop/pull/185
