### ISSUE TITLE
Delete URL

### ISSUE THREAD

**Issue by gpillot** [caido/caido#75]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

In the overview or in the intercept history, it is not possible to delete a URL.

### Use cases

Right-click to the URL and delete button to confirm the delete.

**Comment by Corb3nik** [comment]
Closed via 
https://github.com/caido/caido/issues/578
https://github.com/caido/caido/issues/274
