### ISSUE TITLE
Double clicking on Intercept or Convert sidebar tab opens blank tab

### ISSUE THREAD

**Issue by bebiksior** [caido/caido#752]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

When you double-click on the Intercept or Convert tab in the sidebar the content of `document.querySelector(".c-content").children[0]` gets removed.

![image](https://github.com/caido/caido/assets/71410238/fa383c6b-f5dc-4426-8143-34284868079f)

### How to reproduce
1. Double-click on the Convert or Intercept tab in the sidebar 

### Environment & setup

OS: Windows 11
Caido client: Desktop, Chrome
Caido version: v0.30.4

**Comment by Corb3nik** [comment]
Dammit, I was hoping y'all wouldn't notice this bug...

I actually already fixed it for next release :) Thanks for raising the issue
