### ISSUE TITLE
HTML attributes to allow frontend plugins to retrieve various ID

### ISSUE THREAD

**Issue by Corb3nik** [caido/caido#778]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Add `data-id=` attributes to various components so that frontend plugins can retrieve and do stuff with them.

- Workflow IDs in the /workflows page

**Comment by bebiksior** [comment]
Here are a few of my ideas :D

### Replay page: 
- Session IDs in the navigation items `.c-tab-navigation__tab`
- Session ID for the currently opened session

### HTTP History page
- Request ID for currently opened request in `.c-request`

### Scope page:
- Scope IDs in `c-preset-list__well-entry`

### Scope dropdown (HTTP History, Intercept, WS History, Sitemap, Search):
- Scope ID in `.c-scope-dropdown` so we can retrieve the currently used scope

### Filters page
- Preset IDs in `.c-preset` 

### Workflow page `/workflows/passive/#`
- Workflow ID somewhere to retrieve the current opened workflow (maybe `.c-convert-show`?)

### Current project
- Current project ID in `.c-current-project`
