### ISSUE TITLE
Right click menu improvement

### ISSUE THREAD

**Issue by sw33tLie** [caido/caido#78]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description
On the overview page, when you want to send a request to the replay you need to right-click on it, then hover on `Send` and finally click on `Replay`. 

![image](https://user-images.githubusercontent.com/47645560/143248039-f26170ce-1581-452a-b3d8-0309bf52bd29.png)
While that's the only item on the menu as of now, I very much fear it will eventually become like this: https://twitter.com/sw33tLie/status/1425873499546075136

I think the most commonly used features shouldn't be in a submenu, or be in the main menu too.
I know this sounds like a very small thing, but extra clicks add up soon :)

**Comment by Sytten** [comment]
Great idea, I think this could be a "favorites" list that is pinned at the top of the right click.

**Comment by Corb3nik** [comment]
Send-to actions have been moved to the root menu
