### ISSUE TITLE
Can't type in Replay editor

### ISSUE THREAD

**Issue by Corb3nik** [caido/caido#781]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

Some users can't type in the replay editor. 

There doesn't seem to be any errors in the console + we don't have any steps to reproduce yet.

The affected user is using `macOS Monterey 12.7.3`

**If anyone else has this issue, please comment your OS/version so we can try to reproduce the bug**

**Comment by notakodr** [comment]
Yes same issue here..  macOS Monterey 12.7.3 can only use DELETE key when trying to edit request. Also no typing in many other fields, like scope etc...

**Comment by Sytten** [comment]
@Corb3nik we have 3 reports on this, all on Monterey. So it's likely a bug due to that specific webkit version.

**Comment by Corb3nik** [comment]
@dontsaynetwork I don't think we'll be able to work on this issue anytime soon, so if you're able to upgrade your OS that would be best.

Alternatively, you could use Caido CLI + Firefox/Chrome, that's known to work without any issues AFAIK.

**Comment by Corb3nik** [comment]
Also happens on Big Sur 11.6 https://discord.com/channels/843915806748180492/897575154526330960/1216105445761093664

**Comment by Corb3nik** [comment]
Could be related to this? https://github.com/tauri-apps/tauri/discussions/3541

**Comment by Cache-Money** [comment]
Having this issue on Windows 10 Caido v0.39. Happens randomly where I can't type in any input fields and I have to restart the app.
