### ISSUE TITLE
Resizeable replay box 

### ISSUE THREAD

**Issue by Iieitaimus** [caido/caido#786]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description
When we are getting a lot of sessions in Replay tab, selected request gets smaller making it harder to manipulate. Making upper box resizeable same as Collections box should resolve this problem.

![caido](https://github.com/caido/caido/assets/51837943/9de67642-b0ae-4a85-842f-f91844e7005f)

### Use cases
Improved visibility in crowded replay tab

**Comment by Corb3nik** [comment]
@Iieitaimus Have you considered just closing the tabs? The tabs aren't deleted when you close them (you can retrieve them from the collections section on the left side).

The whole idea around the collections system is that your tab bar can remain small since you can delete them freely.

**Comment by Iieitaimus** [comment]
Oh that make sense
