### ISSUE TITLE
Chrome rendering error in Docker image due to missing dependencies

### ISSUE THREAD

**Issue by 0xA1F1E** [caido/caido#790]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

Caido is unable to render a preview of an HTTP request when deployed through Docker. An error is thrown in the logs telling us that Chrome is missing dependencies.

### How to reproduce

1. Deploy the latest Caido Docker image: `docker run --rm -p 7000:8080 caido/caido:latest`
2. Login and setup a project
3. Proxy any HTTP request through Caido
4. Select HTTP request and click on 'Preview' in the response window
5. Install rendering engine, wait until completed
6. Notice the error `An unknown rendering error has occurred` is thrown.

Error message in logs:

`2024-02-27T16:00:40.970307Z ERROR actix-rt|system:0|arbiter:2 RenderService: Rendering error: LaunchIo(Custom { kind: UnexpectedEof, error: "unexpected end of stream" }, BrowserStderr("/home/caido/.local/share/caido/browsers/linux-1045629/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory\n"))`

A quick and dirty fix is to install `chromium` inside the container, which installs all necessary dependencies. Then, rendering works.

`apt update && apt install chromium -y --no-install-recommends`

### Environment & setup

OS: Ubuntu, Docker
OS version: Ubuntu 22.04 (5.15.0-97-generic, amd64) + Docker 25.0.3 (build 4debf41)
Caido client: Chrome
Caido version: 0.32.0

**Comment by Sytten** [comment]
Ha weird that it stopped working... Thanks for reporting, I will look into it.

**Comment by 0xA1F1E** [comment]
Hi, just curious if you've already looked into this, since this issue is still present for me and it would be nice to not install chromium each time when my container gets destroyed 😅 thanks!

**Comment by Sytten** [comment]
@0xA1F1E Sorry been very busy, I didnt have time to look into it yet. Our docker image is public: https://github.com/caido/caido/blob/main/distribution/Dockerfile

**Comment by Sytten** [comment]
Alright so I figured out the dependencies part, but it doesnt like it when I try to run it on macos M1 probably because of qemu. I will have to check on a proper linux machine. @0xA1F1E 
```dockerfile
FROM debian:bookworm-slim

RUN \
  apt-get update && \
  apt-get -y install ca-certificates && \
  apt-get -y install libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
    libdrm2 libexpat1 libgbm1 libglib2.0-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libudev1 \
    libuuid1 libx11-6 libx11-xcb1 libxcb-dri3-0 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 \
    libxi6 libxkbcommon0 libxrandr2 libxrender1 libxshmfence1 libxss1 libxtst6 && \
  apt-get clean

RUN groupadd -r caido && useradd --no-log-init -m -r -g caido caido

COPY caido-cli /usr/bin/caido-cli

USER caido

EXPOSE 8080

ENTRYPOINT ["caido-cli"]
CMD ["--no-renderer-sandbox", "--no-open", "--listen", "0.0.0.0:8080"]
```

**Comment by Sytten** [comment]
Verified and working
