### ISSUE TITLE
On missing reference, the right panel uses the reference of the last node

### ISSUE THREAD

**Issue by Sytten** [caido/caido#807]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

This is related to #806 

<img width="1474" alt="Screenshot 2024-02-29 at 5 21 18 PM" src="https://github.com/caido/caido/assets/2366731/5d24d027-39b3-4a05-8926-b172684600c7">
<img width="1492" alt="Screenshot 2024-02-29 at 5 21 28 PM" src="https://github.com/caido/caido/assets/2366731/a330c711-9c78-4f52-88b6-a6dfa976ac51">
<img width="1536" alt="Screenshot 2024-02-29 at 5 21 33 PM" src="https://github.com/caido/caido/assets/2366731/f7b02da4-06cc-4cca-9393-237c66cf05ce">

### Steps to reproduce

Link start -> node a
Link node a -> node b
Link node b -> end

Notice that end.data points to node a when it should point to node  b

**Comment by Corb3nik** [comment]
Closing, can't seem to reproduce this anymore.
