### ISSUE TITLE
Add response info in replay page

### ISSUE THREAD

**Issue by sw33tLie** [caido/caido#81]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

When sending a request using the replay, Caido doesn't show any info related to the response size and time it took to get a response.
That's super useful to have and I think it should be added as soon as possible.
It'd be nice to show the full size, but also the headers and body size separately.

Thanks!

**Comment by Corb3nik** [comment]
Task list:
- [x] #259 
- [ ] #260
