### ISSUE TITLE
Add a new dashboard tab to track discovered issues

### ISSUE THREAD

**Issue by Brum3ns** [caido/caido#813]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

A new dashboard tab in Caido would make it possible to store detected behaviors and issues in an organized dashboard from all sources. This would allow you to have a more clear overview of your pentest for each target.

### Use cases
For example, if you discover an issue manually, you can right-click on your request and send a custom issue with a description/severity level to the dashboard. The workflows can also benefit from this by automaticly forward discovered issues they find to the dashboard (Ex as a node).

**Comment by rew1nter** [comment]
Will this be similar to having notes or does caido have separate plans for notes?
