### ISSUE TITLE
Student should get Assistant credits

### ISSUE THREAD

**Issue by Sytten** [caido/caido#816]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

We changed our internal plans stuff in december and it broke the credits system for students (they used to be on the Pro plan but now they are on a Student plan). I need to fix it.

**Comment by fuomag9** [comment]
I think this is fixed now!

**Comment by Sytten** [comment]
Yes I fixed it this morning!
