### ISSUE TITLE
Active Workflows

### ISSUE THREAD

**Issue by fuomag9** [caido/caido#818]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

I'd like to send a specific request (or even multiple ones at the same time) to a specific workflow, so I can run a workflow that uses `$CAIDO_URL` env variable manually without the need to intercept the request

### Use cases

Manual testing, similar to burp feature of "Send to XXXX estension"

**Comment by Sytten** [comment]
This is essentially the active workflow system that is coming soon
