### ISSUE TITLE
Fast clicks on multiple intercept rows can slow down the UI

### ISSUE THREAD

**Issue by sw33tLie** [caido/caido#82]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

Fast clicks on multiple requests in the intercept view can make Caido stuck, especially when requests with big response sizes are involved.
From the terminal I see the backend is sending a query for each click: maybe the previous query should be aborted if a new click happens and it didn't end yet?
![image](https://user-images.githubusercontent.com/47645560/143258713-6b128f3d-575f-4a0c-ba8a-e2397a9b9174.png)

Thanks!

**Comment by sw33tLie** [comment]
To make the experience smoother, it might make sense to preload the request pointed by the mouse cursor, before a click actually happens.
Of course, this requires some attention as you don't want to send hundreds of requests while moving your mouse around.

**Comment by Corb3nik** [comment]
I have a feeling this will be fixed via #5
