### ISSUE TITLE
Add a variable for the project name to use in workflows

### ISSUE THREAD

**Issue by h3xitsec** [caido/caido#822]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Have a variable for the current project name that we can use in workflows bash node. Like $CAIDO_URL
I could see a use case for a "INSCOPE" boolean as well.

### Use cases

I use passive workflows to collect url informations (paths, keys, values, urls) and grep urls against gf patterns. It would be nice to store the results in folders named after the current project

**Comment by Corb3nik** [comment]
Closed via https://github.com/caido/proxy-backend/pull/993
