### ISSUE TITLE
Add option to delete and empty collection

### ISSUE THREAD

**Issue by fuomag9** [caido/caido#823]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

The is currenty no way to delete or empty a collection and sessions have to be deleted manually, which can be time-consuming

![image](https://github.com/caido/caido/assets/1580624/73438047-6feb-457c-a6ec-ead7af28314d)

### Use cases

Better UX, faster and easier to manage requests

**Comment by Corb3nik** [comment]
Tracked in https://github.com/caido/caido/issues/858
