### ISSUE TITLE
Implementation of URL Decode on Hovering The Cursor

### ISSUE THREAD

**Issue by naaaash** [caido/caido#824]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Can URL decode on hovering the cursor be implemented? It kinda becomes easier/quicker to read when hunting on apps like Facebook where most of the graphQL mutation/operations are URL encoded in the POST body. Attaching a screenshot for reference - 

<img width="442" alt="Screenshot 2024-03-07 at 6 43 05 PM" src="https://github.com/caido/caido/assets/41327438/feb84840-94a2-488c-a62c-988570697a02">

**Comment by Sytten** [comment]
I feel this is a good thing for a UI plugin

**Comment by sw33tLie** [comment]
Not on hover but this is available now in evenbetter: https://github.com/bebiksior/EvenBetter
