### ISSUE TITLE
Forgot password mechanism is not working properly: repeated Loop

### ISSUE THREAD

**Issue by ArindamKashyap11** [caido/caido#825]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

When a user attempts to reset their password using the "Forgot password" option on the CAIDO dashboard login page, they are redirected to the password recovery page. After entering their email address and initiating the password recovery process, an email containing a recovery link is sent to the user's email address.

However, upon clicking on the recovery link from the email, users are redirected back to the password recovery page instead of being taken directly to the password reset page. The recovery page prompts the user to enter their email address again, creating an endless loop without allowing the user to reset their password successfully.

### How to reproduce

1. Go to the CAIDO dashboard login page.
2. Click on the "Forgot password" option.
3. Enter a valid email address and submit.
4. Check the email inbox and click on the recovery link.
5. Observe that instead of being redirected to the password reset page, the user is taken back to the password recovery page.
6. The recovery page prompts the user to enter their email address again.
![caido](https://github.com/caido/caido/assets/48338641/931a8c48-987e-4eaa-9924-77d4407ab2d0)

### Environment & setup

OS: Windows 
OS version: 10
Caido client: Microsoft edge
Caido version:  0.32.1

**Comment by Sytten** [comment]
@Corb3nik and I tested independently and it seems to work on our side (chrome and firefox).
I will try to do it on windows, but if you can check that you don't have an extension or something blocking the request.
Any console log is appreciated too!

**Comment by ArindamKashyap11** [comment]
Hi @Sytten thanks for responding. I have tested again today and its working. Thank you!
