### ISSUE TITLE
Bulk select replay tabs to delete them

### ISSUE THREAD

**Issue by sw33tLie** [caido/caido#83]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

It would be nice to have the ability to bulk-select replay tabs by holding CTLR so that we could bulk delete them.
Thanks!

**Comment by Corb3nik** [comment]
Going to track this issue in https://github.com/caido/caido/issues/612 since it has more upvotes.
