### ISSUE TITLE
Shortcuts not preserved when caido updated

### ISSUE THREAD

**Issue by shriyanss** [caido/caido#843]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

When updating caido version, the app doesn't seem to preserve the custom shortcuts

### How to reproduce

- I was using the old caido version, i.e. 0.32.1
- I has custom settings for shortcut, like cmd+enter send requests in both replay and intercept tab
- When I updated the version to 0.33.0 (the latest one), those settings were not there

### Environment & setup

OS: Mac OS
OS version: Sonoma 14.1.1
Caido client: Caido Desktop
Caido version: 0.32.1

**Comment by Corb3nik** [comment]
Hey @shriyanss 👋 With the release of Caido 0.34.0, did your shortcuts reset again?

**Comment by shriyanss** [comment]
Hi @Corb3nik,

The custom shortcuts were preserved

**Comment by Corb3nik** [comment]
Great, thank you
