### ISSUE TITLE
Add JSON functions to sdk in JS node

### ISSUE THREAD

**Issue by VasilyKaiser** [caido/caido#848]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Add JSON functions like these:
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

### Use cases

- Parse input to the JS node as JSON or after some manipulation of the input.
- Easily generate desired JSON structure.

**Comment by Rhynorater** [comment]
Woah, how is this not in the runtime?

**Comment by Sytten** [comment]
We use a very barebone engine called quickjs, so we need to implement all the functions.

**Comment by VasilyKaiser** [comment]
We have this actually!

![image](https://github.com/caido/caido/assets/78181427/90ab1702-8fb9-471a-b571-9814f35abed5)
