### ISSUE TITLE
Add global search feature

### ISSUE THREAD

**Issue by sw33tLie** [caido/caido#85]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

We need a way to start a global search over all HTTP requests known by Caido.
This is useful for multiple use cases, but here's an example.

When testing the reset password functionality of a webapp, you want to search for the reset token you received via email.
If that token was in a request before opening it from your mail, it'd be a bug.

As of now, there's no way of testing that with Caido as far as i know.
Thanks!

**Comment by Sytten** [comment]
Related to https://github.com/caido/caido/issues/4
