### ISSUE TITLE
Custom pages do not load after refresh

### ISSUE THREAD

**Issue by bebiksior** [caido/caido#850]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description
Refreshing Caido while being on custom page added via new Caido Frontend API will throw an error, probably because the custom JS has not been executed yet and the custom page doesn't exist for Caido.

### How to reproduce 
1. Put the following Custom JS code:
```javascript
Caido.navigation.addPage("/custom-page", {
      body: () => Caido.ui.button({label:"hello"}),
      topbar: () => Caido.ui.button({label:"hello"})
})

Caido.sidebar.registerItem("My custom page", "/custom-page", {
      icon: "fas fa-arrow-left",
      group: "Overview",
})
```
2. Navigate to the custom page
3. If you are on **Caido desktop**: open the DevTools  and click CTRL + R, if you are on **browser** just refresh the page.
4. After refresh, the Caido will throw an error and a blank page.

### Environment & setup

OS: Mac OS
OS version: 14.4
Caido client: Caido Desktop, Browser

**Comment by Corb3nik** [comment]
Added a redirect back to the homepage as discussed in discord
