### ISSUE TITLE
Support zstd content-encoding

### ISSUE THREAD

**Issue by rew1nter** [caido/caido#854]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description
It looks like caido fails to parse the HTML, thus the page doesn't load when you visit a facebook profile. I've tested this without caido and via burp, in both cases the page loads correctly
![image](https://github.com/caido/caido/assets/64508791/44d4b34a-6d15-461a-b340-70061630f0d3)

### How to reproduce
1. Make sure the browser is proxying via caido
2. Open a new chrome tab so there's no cache
3. Visit a Facebook profile 
4. See that it doesn't load

### Environment & setup

OS: Arch
OS version: 6.7.9-zen1-1-zen
Caido client: Chromium
Caido version: Caido 0.33.0

**Comment by Sytten** [comment]
Yeah we don't currently support the CE so this is likely the issue, you can bypass it for now with a Match&Replace rule.
I will try to add it soon since this is a standard compression.

**Comment by rew1nter** [comment]
> you can bypass it for now with a Match&Replace rule

So do I just remove the response header?

**Comment by Sytten** [comment]
You replace/remove the `Accept-Encoding` [header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding). This seems to be due to Chrom 123 that shipped with zstd support 30 days ago. I am adding it for the next release.
