### ISSUE TITLE
Null payload marker in automate is a space instead of empty string

### ISSUE THREAD

**Issue by sw33tLie** [caido/caido#861]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

The null payloads marker in the intruder ends up being a space when sending automate requests.
This is problematic since I was attempting a smuggling attack and I had to add 1 to my content length to take that into account

To be honest, there should be no marker at all for null payloads in automate

**Comment by Sytten** [comment]
I need a bit more information on where you placed the marker in the request.
I was looking at the code and in theory it just puts back what was under the marker, nothing less nothing more.

**Comment by Corb3nik** [comment]
@Sytten this is related to the frontend, not the backend. Empty markers indeed add a space.

**Comment by sw33tLie** [comment]
Yes, as @Corb3nik said.
IMHO you should remove the marker for null payloads entirely
