### ISSUE TITLE
Shell node fails to spawn due to too large request/response

### ISSUE THREAD

**Issue by Sytten** [caido/caido#868]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

Many OS have a 4M or less size limit on environment variables. This means if we try to pass a request that is large it will fail to spawn the process.

Alternatives possible:
1. Temporary files (not ideal for IO)
2. STDIN with `{ "request":"...", "response":"..."}`
3. Multiple STDIN write (once for request, once for response)

**Comment by Rhynorater** [comment]
Stdin works!

**Comment by Sytten** [comment]
> Stdin works!

Json or two write/read?

**Comment by Rhynorater** [comment]
Def JSON
