### ISSUE TITLE
No response text when crafting a request from scratch in the replay tab

### ISSUE THREAD

**Issue by sw33tLie** [caido/caido#87]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

If you craft a request from scratch in the replay tab, by pressing `New Request`, then writing down the request text and configuring the host/port, you may have luck and get your response the first time you send the request.
However, if you continue sending the same request, sooner or later you will have an empty response text, even if the request is actually sent.

![image](https://user-images.githubusercontent.com/47645560/143268616-329c8ac5-bd1a-4fcf-9c8d-f04ea27f553d.png)

This behaviour doesn't happen when using a request sent to the replay from the intercept page.

**Comment by Corb3nik** [comment]
Hey @sw33tLie, thanks for the issue :)

I'm having a hard time reproducing this. I'm using the following setup:
- Burp Suite collaborator host
- GET request

I've sent the same request over a 100 times and haven't managed to get a blank response.

In general, I usually get blank responses when I send a request and forget to add the trailing \n\n at the end of a request. Could that maybe be the issue here?

Sending 
```
GET / HTTP/1.1
Host: google.com
```

will cause a blank response, but not:

```
GET / HTTP/1.1
Host: google.com

**Comment by Corb3nik** [comment]
<img width="1369" alt="Screen Shot 2021-11-29 at 10 54 11 PM" src="https://user-images.githubusercontent.com/6225588/143982998-979fb0e0-bfc9-43e6-9393-ce78e4e94d01.png">

**Comment by sw33tLie** [comment]
Hmm sorry this might have been a mistake on my side, a noob mistake I'd add :facepalm: 
I can't reproduce it anymore, I'm starting to think that I was indeed missing those two \n at the bottom.

However, I can say that those bottom \n have always caused many issues according to my past experience (e.g: a triager on a bug bounty platform couldn't reproduce an issue after copy-pasting a request lacking those newlines).
I think it would be nice to have a warning message/icon when that scenario happens: useful after a tiring day of testing :smile:

**Comment by Corb3nik** [comment]
Yep definitely! For starters, adding the line numbers from #92 will help a bit.

As for a warning message, I'll make a separate issue for this. The warning's a good idea but I don't know where to put it yet.
