### ISSUE TITLE
HTTPQL string value doesn't allow backslash sequences

### ISSUE THREAD

**Issue by Corb3nik** [caido/caido#879]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

HTTPQL string values are too restrictive and don't allow sequences such as `\s` and `\'`.

**Comment by teelrabbit** [comment]
Can you please provide some more details regarding the issue.

**Comment by Sytten** [comment]
@teelrabbit What do you need to know exactly? This is due to our language definition.

**Comment by Sytten** [comment]
This is fixed AFAIK with the latest changes in HTTPQL, it was due to the usage of `JSON.parse` which I removed, now the string keeps the escape characters correctly.
