### ISSUE TITLE
Frontend API - Add settings item

### ISSUE THREAD

**Issue by Corb3nik** [caido/caido#882]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Add an API call to allow plugin developers to add items to the settings menu bar

**Comment by Sytten** [comment]
Should we plan for plugin storage on the backend?
