### ISSUE TITLE
Implement show response in browser

### ISSUE THREAD

**Issue by fuomag9** [caido/caido#884]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Implement a feature similar to that present in burp, where responses can be shown in the browser by right clicking

### Use cases

Debug responses in browser

**Comment by Rhynorater** [comment]
Duplicate of https://github.com/caido/caido/issues/165.

**Comment by Rhynorater** [comment]
Potential dupe of @Sytten here too: https://github.com/caido/caido/issues/411 with #165

**Comment by fuomag9** [comment]
Closing as dupe of #165 and #411
