### ISSUE TITLE
Replay responses randomly scroll when resending a request

### ISSUE THREAD

**Issue by sw33tLie** [caido/caido#886]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

1. Send a replay request
2. Make sure the scrollbar is at the top
3. Resend
4. For some reason now it's around the middle of the page

**Comment by Corb3nik** [comment]
This one is a bit hard to reproduce. I was able to reproduce a similar bug in the HTTP History page which should hopefully fix it in Replay.

If the next release (after v0.35.0) still doesn't fix this, let me know :)
