### ISSUE TITLE
Duplicating a stuck replay tab gets you another stuck tab

### ISSUE THREAD

**Issue by sw33tLie** [caido/caido#89]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

When duplicating a tab of a request that's stuck (pending response), the new request will also be stuck.
Combined with the lack of a cancel button this is a big issue as of now.

To easily reproduce this, simply change the port of a request to one that certainly doesn't reply.

Thanks!

**Comment by Corb3nik** [comment]
Fixed via replay task cancellation
