### ISSUE TITLE
Response processing can exhaust memory

### ISSUE THREAD

**Issue by Corb3nik** [caido/caido#895]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

> when reading the response from the remote server, Caido doesn't limit the response size. [...] I could exhaust 32GB of memory with a single request by streaming the response infinitely.

### How to reproduce

Run a server with this code
```go
package main

import (
        "bytes"
        "fmt"
        "net/http"
        "time"
)

func handle(w http.ResponseWriter, r *http.Request) {
        cn, ok := w.(http.CloseNotifier)
        if !ok {
                http.NotFound(w, r)
                return
        }
        flusher, ok := w.(http.Flusher)
        if !ok {
                http.NotFound(w, r)
                return
        }

        w.WriteHeader(http.StatusOK)
        flusher.Flush()
        for {
                select {
                case <-cn.CloseNotify():
                        fmt.Println("disconnected")
                        return
                default:
                        w.Write(bytes.Repeat([]byte("a"), 100000000))
                        flusher.Flush()
                }
                time.Sleep(10 * time.Millisecond)
        }
}

func main() {
        http.HandleFunc("/", handle)
        fmt.Println(http.ListenAndServe(":28080", nil))
}
```

Send a request to it through Caido

### Environment & setup

OS: 
OS version: 
Caido client: 
Caido version:

**Comment by Sytten** [comment]
Response will now be limited to 1GB, we will add a setting for that eventually
