### ISSUE TITLE
Frontend API - Storing/retrieving data

### ISSUE THREAD

**Issue by bebiksior** [caido/caido#899]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description
A function in the Caido API that will allow us to read/write plugin data. This is currently possible with `localStorage` but I think it would be better to have access to a folder like `/Caido/Plugins/EvenBetter` and store data there.

### Use cases
This would help us in making Caido plugins that need to store/retrieve data.

**Comment by Corb3nik** [comment]
After further discussion, the main use case right now seems to be to store a list of the user's custom JS / custom CSS.

It's currently possible with localstorage, but with the disadvantage that it won't sync if you switch to another client such as a different browser.
