### ISSUE TITLE
Edit and replay request in passive workflow

### ISSUE THREAD

**Issue by fuomag9** [caido/caido#901]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Add new passive workflows nodes for:
 - making new requests 
 - modify HTTP requests

### Use cases

Make new requests with modifications automatically to test for things
Easier to use workflows

**Comment by Sytten** [comment]
Closing in favour of https://github.com/caido/caido/issues/902 since it is included in that node
