### ISSUE TITLE
Support arrow keys navigation in the overview page

### ISSUE THREAD

**Issue by sw33tLie** [caido/caido#91]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Arrow keys should be supported to navigate in the overview page:
![image](https://user-images.githubusercontent.com/47645560/143278309-c0beeedc-2a3c-43e9-af29-25b77dfffb0b.png)

This would make it easy to have a quick look at multiple requests.

**Comment by Corb3nik** [comment]
Closed via https://github.com/caido/proxy-frontend/pull/996
