### ISSUE TITLE
Cannot download exports on vivaldi

### ISSUE THREAD

**Issue by fuomag9** [caido/caido#918]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

I cannot download the exports, as the download button will open an `about:blank` page

### How to reproduce

- Use vivaldi
- Make an export
- Click on download
 ![image](https://github.com/caido/caido/assets/1580624/894db184-9c69-4393-87ac-e330d692b9d9)
- an `about:blank` page will open
![image](https://github.com/caido/caido/assets/1580624/68ab5859-35ac-4341-b0d2-4811cfbf8a5c)

### Environment & setup

OS: macOS
OS version:  14.4.1 (23E224)
Caido client: docker, vivaldi
Caido version: 0.34.1

**Comment by fuomag9** [comment]
Note: this probably shares the same root cause as #808, but I'm making it a separate issue for now

**Comment by fuomag9** [comment]
Browser bug, downloading blobs fails with HTTP pages. Suggested fix for users for now is to use HTTPS on the caido UX page

**Comment by Corb3nik** [comment]
Closing this. Tested on `7.0.3495.18 (Stable channel) (arm64)`, seems to be fixed 🎉
