### ISSUE TITLE
Non-http compliant response do not work in replay interface and fail with "parsing error"

### ISSUE THREAD

**Issue by fuomag9** [caido/caido#930]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

Non-http compliant response do not work in replay interface and fail with `Parsing error`

HTTP history
![image](https://github.com/caido/caido/assets/1580624/42b4674d-3c59-4a3e-b641-946799752d72)

Replay
![image](https://github.com/caido/caido/assets/1580624/08de0d9b-1ca2-4258-bebc-5a1ec9d6b577)

### How to reproduce

Send a request to a non-compliant http server that only sends text as a response (maybe netcat?)

### Environment & setup

OS: macOS
OS version: 14.4.1 (23E224)
Caido client: Vivaldi, docker
Caido version: 0.35.0

**Comment by Sytten** [comment]
This is a frontend issue when the backend returns both an error and some data
