### ISSUE TITLE
Deduplicate issues

### ISSUE THREAD

**Issue by sw33tLie** [caido/caido#939]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

Allow us to avoid saving multiple findings if it's the same workflow, path etc

**Comment by Sytten** [comment]
A user suggested we implement a deduplication key.
> for example if I have a workflow looking for AWS Cognito pool IDs, id love to be able to create like {workflow_name}.{hostname} so that I can only have one finding per host. BUT also the possibility of diong {workflow_name}.{hostname}.{path} so that I can have multiple findings per host** 

This is a very good idea since it is very flexible and we don't have to create a UI for it or filters, you decide what you want to include in that key.

See https://discord.com/channels/843915806748180492/1237827511463972884/1239700760082645072
