### ISSUE TITLE
Drag and Drop request from collections, select text automatically

### ISSUE THREAD

**Issue by Sicks3c** [caido/caido#949]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

Dragging and dropping a request between collections can be difficult when the collection is open, as it automatically selects the text.

### How to reproduce

https://discord.com/channels/843915806748180492/1222955801828921364/1228425047123824721

### Environment & setup

OS:Mac M1
Caido client:Desktop
Caido version:0.35.0

**Comment by bebiksior** [comment]
`.c-tree-node-name__label` has only `user-select: none;` which doesn't work on Safari.
Fixed it with this custom CSS:
```css
.c-session-tree .c-tree-node-name__label {
   -webkit-user-select: none;
}
```
