### ISSUE TITLE
Request body blinks when sending a request from a new tab

### ISSUE THREAD

**Issue by sw33tLie** [caido/caido#953]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

The request body in replay blinks when sending a request from a new tab.
This doesn't happen after anymore the first request has been sent.

### Environment & setup

OS: 
OS version: 
Caido client: 
Caido version:

**Comment by Corb3nik** [comment]
Can't seem to reproduce this anymore.
