### ISSUE TITLE
Preset filters not working

### ISSUE THREAD

**Issue by fuomag9** [caido/caido#954]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description

Filter presets do not work

### How to reproduce

Create a filter:

![image](https://github.com/caido/caido/assets/1580624/43dca8c6-cd79-44ab-8899-04cd10e5bfe9)

Try to use a filter:
![image](https://github.com/caido/caido/assets/1580624/c89183aa-b7af-48a1-9948-0ab507380617)

![image](https://github.com/caido/caido/assets/1580624/2c1dc438-f859-4752-9789-bb85b16cd9a0)

Using the filter manually works:

![image](https://github.com/caido/caido/assets/1580624/dfe01706-be3c-47fd-9b3f-9db047daeb09)

### Environment & setup

OS: macOS
OS version: 14.4.1 (23E224)
Caido client: Vivaldi, docker
Caido version: 0.35.0

**Comment by Corb3nik** [comment]
Closed via https://github.com/caido/proxy-frontend/pull/1438
