### ISSUE TITLE
Add a warning message when sending a request without the trailing \r\n\r\n

### ISSUE THREAD

**Issue by Corb3nik** [caido/caido#96]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description

We've all done it before: we create a request and forget to add a \r\n\r\n, resulting in a blank response or a response that times out.

It would be nice to have a solution for this inconvenience.

Some ideas:
- Automatically add \r\n\r\n after clicking `Send`
    * Downside: A bit intrusive, as we'd like to prevent Caido from modifying our requests as much as possible
- Add a warning message / icon somewhere in the frontend when the currently viewed request lacks the \r\n\r\n 
    * Where do we put it? Maybe it could be IDE-style, where you'd get a red highlight warning you. (Imagine the following, but the red line would only be aligned to the `last` line of the request)
    <img width="560" alt="Screen Shot 2021-11-30 at 9 29 16 AM" src="https://user-images.githubusercontent.com/6225588/144065876-2b2d65a3-298c-4a37-b12b-96666ff5cd89.png">
    
Other ideas are welcome :)

**Comment by sw33tLie** [comment]
I don't like the idea of adding it automatically very much, too intrusive for me as well.

Maybe we could use the area below the search bar for that.
I think that #81 is something to keep in mind when choosing this.

Maybe it could be:
- Area below the request search: trailing \n warnings/other potential info
- Area below the response search: response size, server conn errors etc?

**Comment by Corb3nik** [comment]
https://user-images.githubusercontent.com/6225588/190265561-9b1ac54d-4bdd-4acb-96cf-35e75f8e5b90.mov
