### ISSUE TITLE
Pop up in automate goes under column header

### ISSUE THREAD

**Issue by rew1nter** [caido/caido#981]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Bug description
![image](https://github.com/caido/caido/assets/64508791/bd3f1120-be34-47de-b7b5-54d52612a0e0)

### Environment & setup

Caido version: Caido 0.35.0

**Comment by Sytten** [comment]
It might be already fixed

**Comment by Corb3nik** [comment]
Not fixed yet :)

**Comment by Corb3nik** [comment]
This has been fixed in v0.36.0
