### ISSUE TITLE
Add multi-cursor selection and range selection

### ISSUE THREAD

**Issue by gordianbahri** [caido/caido#984]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help us know what to work on
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Description
Add the possibility to select an item then press `Shift` then select another item, to select every item in between -> range selection
Add the possibility to select an item then press `Strg` then select another item, to add this item to the selection -> multi-cursor selection
(These are basic control shortcuts that can be found in almost every modern GUI.)

### Use cases
The use cases can vary. Here are some of them:
For bulk selecting multiple, but specific items to:
1. Delete them.
2. Send them to automate.
3. Send them to replay.
4. Highlight them in a specific color.

**Comment by Sytten** [comment]
We improved a lot this in v0.36.0, closing for now but let us know if we need to re-open it :)
